Repository knative/operator, pull requests merged in 2020-12, with the labels that each got.

#372 Add the missing 0.18 and 0.19 eventing manifests
  cmd/operator/kodata/knative-eventing/0.18.4/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/5-eventing-sugar-controller.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#375 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#377 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#378 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#380 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#379 Add the field spec.additionalManifests into the CRD's
  config/300-eventing.yaml
  config/300-serving.yaml
  pkg/reconciler/common/stages.go
Labels: approved, cla: yes, lgtm, size/S

#383 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#386 Point all dependencies to 0.19 branches properly
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#384 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#385 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#381 Add the transformer for pingsource to keep the env vars and replicas
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform.go
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, cla: yes, lgtm, size/L

#390 [release-0.18] Add the transformer for pingsource to keep the env vars and replicas
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform.go
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, cla: yes, lgtm, size/L

#391 Add the manifests of eventing 0.19.3
  cmd/operator/kodata/knative-eventing/0.19.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/5-eventing-sugar-controller.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#389 [release-0.19] Add the transformer for pingsource to keep the env vars and replicas
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform.go
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, cla: yes, lgtm, size/L

#410 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#411 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#412 [Automated] Fix misspellings
  cmd/operator/kodata/knative-eventing/0.16.0/2-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/2-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.16.2/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.16.3/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.16.4/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/2-eventing-core.yaml
Labels: approved, cla: yes, lgtm, size/M

#413 [Automated] Format Go code
  pkg/packages/release_test.go
Labels: approved, cla: yes, lgtm, size/XS

#414 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#409 Add the missing serving and eventing manifests
  cmd/operator/kodata/knative-serving/0.18.3/4-net-istio.yaml
Labels: approved, cla: yes, lgtm, size/XS

#392 [release-0.19] Add the missing serving and eventing manifests for release-0.19
  cmd/operator/kodata/knative-eventing/0.17.8/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.19.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-serving/0.18.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.18.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.18.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.18.3/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.18.3/5-serving-post-install-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XXL
