Repository knative/operator, pull requests merged in 2020-07, with the labels that each got.

#173 Add 0.15.2 of serving and eventing manifests
  cmd/operator/kodata/knative-eventing/0.15.2/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.2/2-upgrade-to-v0.15.2.yaml
  cmd/operator/kodata/knative-eventing/0.15.2/3-storage-version-migration-v0.15.2.yaml
  cmd/operator/kodata/knative-serving/0.15.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.15.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.15.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.15.2/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.15.2/5-serving-storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#174 Add 0.15.2 of serving and eventing manifests (#173)
  cmd/operator/kodata/knative-eventing/0.15.2/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.2/2-upgrade-to-v0.15.2.yaml
  cmd/operator/kodata/knative-eventing/0.15.2/3-storage-version-migration-v0.15.2.yaml
  cmd/operator/kodata/knative-serving/0.15.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.15.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.15.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.15.2/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.15.2/5-serving-storage-version-migration.yaml
Labels: approved, cla: yes, size/XXL

#175 [Release-0.14] Update the manifestival to fix the non-default ns for eventing
  Gopkg.lock
  Gopkg.toml
  third_party/VENDOR-LICENSE
  vendor/github.com/manifestival/client-go-client/client.go
  vendor/github.com/manifestival/client-go-client/pkg/dynamic/interface.go
  vendor/github.com/manifestival/client-go-client/pkg/dynamic/rest_mapper_resource_interface.go
  vendor/github.com/manifestival/client-go-client/pkg/dynamic/unsafe_resource_interface.go
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/options.go
  vendor/github.com/manifestival/manifestival/source.go
  vendor/github.com/operator-framework/operator-sdk/pkg/restmapper/dynamicrestmapper.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
Labels: approved, cla: yes, size/XXL

#177 [Release-0.14] Update the serving manifests into 0.14.2
  cmd/serving-operator/kodata/knative-serving/1-serving-crds.yaml
  cmd/serving-operator/kodata/knative-serving/2-serving-core.yaml
  cmd/serving-operator/kodata/knative-serving/3-serving-hpa.yaml
  cmd/serving-operator/kodata/knative-serving/4-net-istio.yaml
  version/version.go
Labels: approved, cla: yes, size/L

#167 Run e2e tests in arbitrary namespace
  test/README.md
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
  test/e2e_flags.go
  test/resources/knativeresources.go
  test/resources/knativeserving.go
Labels: approved, cla: yes, lgtm, size/M

#179 Always return nil from FinalizeKind
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XS

#187 Ignore CRD's when deleting obsolete resources
  pkg/reconciler/common/stages.go
  pkg/reconciler/common/stages_test.go
Labels: approved, cla: yes, lgtm, size/S

#182 Update deps / codegen + turn off krshapedlogic
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#180 Add the tranformer for job resources
  pkg/reconciler/common/job.go
  pkg/reconciler/common/job_test.go
  pkg/reconciler/common/transformers.go
Labels: approved, cla: yes, lgtm, size/L

#192 [release-0.15] Add eventing manifest 0.15.3
  cmd/operator/kodata/knative-eventing/0.15.3/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.3/2-upgrade-to-v0.15.0.yaml
  cmd/operator/kodata/knative-eventing/0.15.3/3-storage-version-migration-v0.15.0.yaml
Labels: approved, cla: yes, size/XXL

#193 Add eventing manifest 0.15.3
  cmd/operator/kodata/knative-eventing/0.15.3/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.3/2-upgrade-to-v0.15.0.yaml
  cmd/operator/kodata/knative-eventing/0.15.3/3-storage-version-migration-v0.15.0.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#194 Update to latest manifestival 0.6.0+
  go.mod
  go.sum
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/README.md
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/dry.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/go.sum
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#204 Remove the useless logstream.Start
  test/e2e/knativeeventingdeployment_test.go
  test/e2e/knativeservingdeployment_test.go
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/knativeeventing_preupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/helpers/dryrun.go
  vendor/knative.dev/pkg/test/helpers/error.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/test/logstream/doc.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/kubelogs.go
  vendor/knative.dev/pkg/test/logstream/null.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#205 Backport fix for infinite reconcile loop
  config/300-eventing.yaml
  config/300-serving.yaml
  test/resources/verify.go
Labels: approved, cla: yes, lgtm, size/M

#203 Prevent infinite reconcile loop
  config/300-eventing.yaml
  config/300-serving.yaml
  test/resources/verify.go
Labels: approved, cla: yes, lgtm, size/M

#181 Add 0.16.0 manifests of knative
  cmd/operator/kodata/knative-eventing/0.16.0/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.16.0/2-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.16.0/3-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.16.0/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.16.0/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.16.0/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.16.0/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.16.0/5-serving-post-install-jobs.yaml
  test/e2e-common.sh
  test/resources/knativeresources.go
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/knativeeventing_preupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#197 OLM metadata for 0.15.1
  deploy/olm-catalog/knative-operator/0.15.1/knative-operator.v0.15.1.clusterserviceversion.yaml
  deploy/olm-catalog/knative-operator/0.15.1/knativeeventings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.15.1/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/knative-serving-operator.package.yaml
Labels: approved, cla: yes, lgtm, size/XL

#207 Add spec version into operator CRD's
  config/300-eventing.yaml
  config/300-serving.yaml
Labels: approved, cla: yes, lgtm, size/XS

#137 Add the logic to determine if upgrade or downgrade is eligible
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#208 Add the missing manifests as of 0.14.0
  cmd/operator/kodata/knative-eventing/0.14.0/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.14.0/2-upgrade-to-v0.14.0.yaml
  cmd/operator/kodata/knative-eventing/0.14.1/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.14.1/2-upgrade-to-v0.14.0.yaml
  cmd/operator/kodata/knative-eventing/0.15.4/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.4/2-upgrade-to-v0.15.0.yaml
  cmd/operator/kodata/knative-eventing/0.15.4/3-storage-version-migration-v0.15.0.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/2-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/3-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.14.0/5-serving-storage-version-migration.yaml
  cmd/operator/kodata/knative-serving/0.14.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.14.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.14.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.14.1/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.14.1/5-serving-storage-version-migration.yaml
  cmd/operator/kodata/knative-serving/0.14.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.14.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.14.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.14.2/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.14.2/5-serving-storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#210 Delete old OLM metadata
  deploy/olm-catalog/knative-serving-operator/0.11.0/knative-serving-operator.v0.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-serving-operator/0.11.0/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-serving-operator/0.12.0/300-serving-v1alpha1-knativeserving-crd.yaml
  deploy/olm-catalog/knative-serving-operator/0.12.0/knative-serving-operator.v0.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-serving-operator/0.12.2/knative-serving-operator.v0.12.2.clusterserviceversion.yaml
  deploy/olm-catalog/knative-serving-operator/0.12.2/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#214 Fix the Kind in the GVK returned by KnativeEventing.
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/operator/v1alpha1/register.go
Labels: approved, cla: no, size/S
