Repository knative/operator, pull requests merged in 2020-11, with the labels that each got.

#342 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#345 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#346 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#347 Add the missing 0.17 and 0.18 manifests for serving and eventing
  cmd/operator/kodata/knative-eventing/0.17.8/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-serving/0.18.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.18.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.18.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.18.2/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.18.2/5-serving-post-install-jobs.yaml
  test/e2e-common.sh
Labels: approved, cla: yes, size/XXL

#351 Fix a few more occurrences of divisive language
  pkg/reconciler/common/testdata/kodata/knative-eventing/0.14.2/test-eventing.yaml
  pkg/reconciler/common/testdata/kodata/knative-eventing/0.15.0/test-eventing.yaml
  pkg/reconciler/common/testdata/kodata/knative-serving/0.14.0/test-serving.yaml
  pkg/reconciler/common/testdata/kodata/knative-serving/0.15.0/test-serving.yaml
Labels: approved, cla: yes, lgtm, size/XS

#350 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#355 Set E2E_UPGRADE_TESTS_SERVING_USE to false for eventing upgrade tests
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#353 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#349 Add namespace injection into the manifests in upgrade tests
  test/e2e-upgrade-tests.sh
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/M

#352 Preserve the env variable KO_FLAGS
  hack/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#294 Install the Istio with the Istio Operator in Prows
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#359 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#370 [release-0.19] Add the support to build the operator image for all platforms
  hack/generate-yamls.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#368 [release-0.19] Add the missing 0.18 and 0.19 eventing manifests
  cmd/operator/kodata/knative-eventing/0.18.4/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.4/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.5/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.19.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.19.2/5-eventing-sugar-controller.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#367 [release-0.18] Add the missing 0.18.6 eventing manifests
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-style.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.18.6/6-eventing-sugar-controller.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#369 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
