Repository knative/operator, pull requests merged in 2020-10, with the labels that each got.

#288 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#293 Add all 0.17.x eventing and serving manifests into the release-0.17
  cmd/operator/kodata/knative-eventing/0.17.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.4/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.5/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.5/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.17.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.17.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.17.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.17.3/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.3/5-serving-post-install-jobs.yaml
Labels: approved, cla: yes, size/XXL

#299 Don't wait for Ksvc to scale to zero
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#300 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#305 lint: previous condition includes return statement, pop else statement
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, cla: yes, lgtm, size/XS

#301 Spelling
  docs/configuration.md
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#308 Remove noop override of docker/docker
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#310 Drop dependency on pkg/errors
  go.mod
  test/resources/knativeeventing.go
  test/resources/knativeserving.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#309 Consolidate the used YAML dependencies to just one
  go.mod
  pkg/reconciler/common/resources_test.go
  pkg/reconciler/knativeeventing/common/defaultbroker.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#325 Removing incorrect pre-job for 0.17.0
  cmd/operator/kodata/knative-eventing/0.17.0/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/6-eventing-post-install-jobs.yaml
Labels: approved, cla: yes, lgtm, size/L

#327 [release-0.17] :lipstick: remvoving incorrect pre-job for 0.17.0 (#325)
  cmd/operator/kodata/knative-eventing/0.17.0/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/6-eventing-post-install-jobs.yaml
Labels: approved, cla: no, size/L

#328 [release-0.18]:lipstick: remvoving incorrect pre-job for 0.17.0 (#325)
  cmd/operator/kodata/knative-eventing/0.17.0/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/6-eventing-post-install-jobs.yaml
Labels: approved, cla: no, size/L

#326 Add support of the major.minor format for spec.version
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
Labels: approved, cla: yes, lgtm, size/L

#323 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#333 Use the hack repository for scripts
  go.mod
  go.sum
  hack/release.sh
  hack/tools.go
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/e2e-common.sh
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#334 [release-0.18] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#335 [Automated] Format Go code
  hack/tools.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#336 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
