Repository knative/operator, pull requests merged in 2020-06, with the labels that each got.

#104 Make the retry logic work to verify the Knative Serving resources
  test/resources/knativeeventing.go
  test/resources/knativeresources.go
  test/resources/knativeserving.go
  test/resources/verify.go
  test/upgrade/knativeeventingpreupgrade_test.go
  test/upgrade/knativeeventingupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/L

#110 Update the library manifestival to v0.5.1-0.20200526175228-b0136214e13f
  go.mod
  go.sum
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/Gopkg.lock
  vendor/github.com/manifestival/manifestival/Gopkg.toml
  vendor/github.com/manifestival/manifestival/README.md
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/options.go
  vendor/github.com/manifestival/manifestival/source.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#115 Change the structure of kodata and read the yamls with the version
  cmd/operator/kodata/knative-eventing/0.14.2/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.14.2/2-upgrade-to-v0.14.2.yaml
  cmd/operator/kodata/knative-serving/0.14.0/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.14.0/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.14.0/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.14.0/4-net-istio.yaml
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeserving/controller.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/S

#118 With 0.15 the MTChannelBasedBroker is the new default broker
  pkg/reconciler/knativeeventing/common/defaultbroker.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
Labels: approved, cla: yes, lgtm, size/XS

#122 Add the manifests of knative at 0.15
  cmd/operator/kodata/knative-eventing/0.15.0/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.0/2-upgrade-to-v0.15.0.yaml
  cmd/operator/kodata/knative-eventing/0.15.0/3-storage-version-migration-v0.15.0.yaml
  cmd/operator/kodata/knative-serving/0.15.0/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.15.0/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.15.0/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.15.0/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.15.0/5-serving-storage-version-migration.yaml
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
  test/upgrade/knativeeventingpreupgrade_test.go
  version/version.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#117 Get the version number by reading the structure of kodata
  go.mod
  go.sum
  pkg/reconciler/common/read_releases.go
  pkg/reconciler/common/read_releases_test.go
  pkg/reconciler/common/testdata/kodata/knative-eventing/0.14.2/dummy-eventing.yaml
  pkg/reconciler/common/testdata/kodata/knative-eventing/0.15.0/dummy-eventing.yaml
  pkg/reconciler/common/testdata/kodata/knative-serving/0.14.0/dummy-serving.yaml
  pkg/reconciler/common/testdata/kodata/knative-serving/0.15.0/dummy-serving.yaml
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
  third_party/VENDOR-LICENSE/golang.org/x/mod/semver/LICENSE
  vendor/modules.txt
  version/version.go
Labels: approved, cla: yes, lgtm, size/L

#124 Fix link for latest release in docs
  docs/installation.md
Labels: approved, cla: yes, lgtm, size/XS

#121 Use the combined operator instead of separated operator
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#123 Add missing namespace
  config/config-logging.yaml
  config/config-observability.yaml
  config/operator.yaml
  config/service_account.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#128 Correcting API doc
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
Labels: approved, cla: yes, lgtm, size/XS

#125 Create the expected deployments based on version
  test/resources/knativeresources.go
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/knativeeventing_preupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/M

#107 Update go.mod to specify the module is go1.14
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#126 Validate the obsolete resources with golang tests
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
  test/e2e_flags.go
  test/resources/knativeresources.go
  test/resources/verify.go
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/knativeeventing_preupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/L

#83 Remove metric reporting in KnativeServing.
  go.mod
  pkg/reconciler/knativeserving/common/stats_reporter.go
  pkg/reconciler/knativeserving/common/stats_reporter_test.go
  pkg/reconciler/knativeserving/controller.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/testing/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#135 Add Spec.Version to the API, but not the CRD yet
  pkg/apis/operator/v1alpha1/common.go
  pkg/reconciler/common/read_releases.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
  test/resources/knativeresources.go
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/knativeeventing_preupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/L

#140 [RELEASE-0.14] Don't delete deployments first explicitly.
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XS

#143 Add the label to all the operator resources
  config/300-eventing.yaml
  config/300-serving.yaml
  config/operator.yaml
  config/role.yaml
  config/role_binding.yaml
  config/service_account.yaml
Labels: approved, cla: yes, lgtm, size/S

#146 correct defaultBrokerClass name in eventing crd description
  config/300-eventing.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#138 Introduce Stages abstraction to simplify manifest post-processing
  pkg/reconciler/common/stages.go
  pkg/reconciler/common/stages_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#145 Add the knative 0.15.1 releases into kodata
  cmd/operator/kodata/knative-eventing/0.15.1/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.1/2-upgrade-to-v0.15.1.yaml
  cmd/operator/kodata/knative-eventing/0.15.1/3-storage-version-migration-v0.15.1.yaml
  cmd/operator/kodata/knative-serving/0.15.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.15.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.15.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.15.1/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.15.1/5-serving-storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#150 [release-0.15]Add the knative 0.15.1 releases into kodata (#145)
  cmd/operator/kodata/knative-eventing/0.15.1/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.1/2-upgrade-to-v0.15.1.yaml
  cmd/operator/kodata/knative-eventing/0.15.1/3-storage-version-migration-v0.15.1.yaml
  cmd/operator/kodata/knative-serving/0.15.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.15.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.15.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.15.1/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.15.1/5-serving-storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#152 Refactor image transformation
  pkg/reconciler/common/images.go
Labels: approved, cla: yes, lgtm, size/L

#151 Fleshing out a more complete Extensions API
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/extensions_test.go
  pkg/reconciler/common/transformers.go
Labels: approved, cla: yes, lgtm, size/S

#149 Comparing target & installed manifests to delete obsolete resources
  pkg/reconciler/common/stages.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#155 Further extension enhancements
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/extensions_test.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#161 Remove temporary functions to cleanup move to combined operator.
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
  pkg/reconciler/upgrade.go
  pkg/reconciler/upgrade_test.go
Labels: approved, cla: yes, lgtm, size/L

#164 Refactor image replacement interface for explicit support of each typ…
  pkg/reconciler/common/images.go
Labels: approved, cla: yes, lgtm, size/M

#163 Add the upgrade test script for eventing
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/L
