Repository knative/operator, pull requests merged in 2020-08, with the labels that each got.

#220 Make clear that deployments are not the only override-able container
  docs/configuration.md
Labels: approved, cla: yes, lgtm, size/S

#226 Set the branch to 0.16 for knative in test case
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/XS

#211 Assorted linting fixes.
  pkg/reconciler/common/extensions_test.go
  test/resources/verify.go
Labels: approved, cla: yes, lgtm, size/S

#235 Add the postdowngrade tests, making sure the downgrade is complete
  test/downgrade/knative_postdowngrade_test.go
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
  test/resources/knativeresources.go
  test/resources/verify.go
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/knativeeventing_preupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/L

#236 Adding istio ignore annotation transformer for jobs
  pkg/reconciler/common/job.go
Labels: approved, cla: yes, lgtm, size/M

#241 Remove the check on obsolete resource, since the downgrade is unstable
  test/downgrade/knative_postdowngrade_test.go
Labels: approved, cla: yes, lgtm, size/XS

#238 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#233 [master] Format markdown
  README.md
  docs/configuration.md
  docs/development.md
  docs/installation.md
Labels: approved, cla: yes, lgtm, size/L

#224 Update to latest manifestival to fix an issue on CRD/v1 transformer
  go.mod
  go.sum
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/README.md
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#147 Add the support to specify customized yamls
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/install.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/stages_test.go
  pkg/reconciler/common/testdata/kodata/knative-eventing/0.16.0/eventing-core.yaml
  pkg/reconciler/common/testdata/kodata/knative-eventing/0.16.0/in-memory-channel.yaml
  pkg/reconciler/common/testdata/kodata/knative-serving/0.16.0/serving-core.yaml
  pkg/reconciler/common/testdata/kodata/knative-serving/0.16.0/serving-hpa.yaml
Labels: approved, cla: yes, lgtm, size/L

#243 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#246 Validate whether spec.version matches the version of manifests
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/testdata/invalid_kodata/knative-serving/0.16.0_unmatched_version/serving-core.yaml
  pkg/reconciler/common/testdata/invalid_kodata/knative-serving/0.16.0_unmatched_version/serving-hpa.yaml
Labels: approved, cla: yes, lgtm, size/L

#247 Add spec.manifests into the CRD's
  config/300-eventing.yaml
  config/300-serving.yaml
  pkg/reconciler/common/install.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
Labels: approved, cla: yes, lgtm, size/M

#251 Add 0.17 manifests into the operator
  cmd/operator/kodata/knative-eventing/0.17.0/1-eventing-pre-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/2-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/6-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/7-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.17.0/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.17.0/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.17.0/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.17.0/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.0/5-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.17.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.17.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.17.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.17.1/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.1/5-serving-post-install-jobs.yaml
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/XXL

#256 [master] Format markdown
  docs/configuration.md
Labels: approved, cla: yes, lgtm, size/XS

#257 Add the label operator.knative.dev/release into the operator resource for release
  hack/generate-yamls.sh
Labels: approved, cla: yes, lgtm, size/XS
