Repository knative/operator, pull requests merged in 2020-05, with the labels that each got.

#58 Remove unneeded comments and format.
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/reconciler/common/config_maps_test.go
  test/crd.go
Labels: approved, cla: yes, lgtm, size/S

#59 Clean up KnativeServing lifecycle and relevant tests.
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/L

#57 Bump ObservedGeneration at the beginning of reconcilation.
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XS

#61 Fix the Kind in the GVK returned by KnativeEventing.
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/operator/v1alpha1/register.go
Labels: approved, cla: yes, lgtm, size/S

#62 Align Eventing conditions with Serving conditions.
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, cla: yes, lgtm, size/L

#63 Collapse common spec fields into a CommonSpec.
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/reconciler/common/images_test.go
  test/resources/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#65 Add an interface for common status mutations.
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
Labels: approved, cla: yes, lgtm, size/M

#67 Fix update-codegen.sh for module usage.
  hack/update-codegen.sh
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XS

#69 Add verify-codegen.sh to be run by presubmit.
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/M

#68 Remove unused generator comments, group the remaining better and general cleanup.
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/register_test.go
  pkg/apis/operator/v1alpha1/zz_generated.defaults.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
Labels: approved, cla: yes, lgtm, size/L

#70 Move the deployment check into common code and add tests.
  pkg/reconciler/common/deployments.go
  pkg/reconciler/common/deployments_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#66 Add remaining KComponent interfaces and implementations.
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/config_maps.go
  pkg/reconciler/common/config_maps_test.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
  test/resources/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#75 Move install routine into common code and add tests.
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#78 Move common transformers to common code.
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#77 Fix job image override
  pkg/reconciler/common/images.go
  pkg/reconciler/common/images_test.go
  pkg/reconciler/common/resources_test.go
  pkg/reconciler/knativeserving/common/gateway_test.go
Labels: approved, cla: yes, lgtm, size/M

#79 Fix copy-paste error
  pkg/reconciler/common/images_test.go
Labels: approved, cla: yes, lgtm, size/XS

#80 Fix deprecated function calls, remove unused code.
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XS

#81 Fix job image override for 0.14 branch
  pkg/reconciler/knativeeventing/common/images.go
  pkg/reconciler/knativeeventing/common/images_test.go
Labels: approved, cla: yes, lgtm, size/M

#84 Consolidate finalizer removal code.
  pkg/reconciler/common/finalizer.go
  pkg/reconciler/common/finalizer_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#74 Update the dependencies and regenerate the client code
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  third_party/VENDOR-LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#86 Update the manifest of eventing to 0.14.2
  cmd/operator/kodata/knative-eventing/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/2-upgrade-to-v0.14.2.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/L

#89 Consolidate and test uninstall logic.
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#90 Provide the link for the latest nightly build
  docs/installation.md
Labels: approved, cla: yes, lgtm, size/XS

#91 Use :nonroot image for the operator.
  .ko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#93 Bump manifestival-client-go-client dependency to drop openshift deps.
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/sigs.k8s.io/controller-runtime/pkg/client/apiutil/LICENSE
  vendor/github.com/manifestival/client-go-client/Gopkg.lock
  vendor/github.com/manifestival/client-go-client/Gopkg.toml
  vendor/github.com/manifestival/client-go-client/README.md
  vendor/github.com/manifestival/client-go-client/client.go
  vendor/github.com/operator-framework/operator-sdk/pkg/restmapper/dynamicrestmapper.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
Labels: approved, cla: yes, lgtm, size/XL

#99 [RELEASE] Pin pkg,test-infra to release-0.15
  go.mod
  go.sum
  hack/update-deps.sh
  pkg/reconciler/knativeserving/common/stats_reporter_test.go
  vendor/golang.org/x/net/http2/h2c/h2c.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/testing/config.go
  vendor/knative.dev/pkg/metrics/utils.go
  vendor/knative.dev/pkg/network/doc.go
  vendor/knative.dev/pkg/network/domain.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
