Repository knative/operator, pull requests merged in 2020-04, with the labels that each got.

#8 Add genreconciler to KnativeServing and KnativeEventing types
  Gopkg.lock
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/stub/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/stub/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/stub/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/stub/reconciler.go
Labels: approved, cla: yes, lgtm, size/L

#9 Reconciler in controller
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/M

#10 Remove rbase
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#13 Respect HA Replicas setting in HPAs
  pkg/reconciler/knativeserving/common/ha.go
  pkg/reconciler/knativeserving/common/ha_test.go
Labels: approved, cla: yes, lgtm, size/M

#16 Update to manifestival 0.5.0
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeeventing/knativeeventing.go
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/overlay/overlay.go
Labels: approved, cla: yes, lgtm, size/M

#20 Add the job to upgrade the broker in eventing for 0.14
  cmd/eventing-operator/kodata/knative-eventing/1-eventing.yaml
  cmd/eventing-operator/kodata/knative-eventing/2-upgrade-to-v0.14.0.yaml
  config/role.yaml
Labels: approved, cla: yes, lgtm, size/S

#32 Use genreconciler framework in the eventing reconciler.
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#35 Remove obsolete finalizer from KnativeServing resources.
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/M

#21 Unify operators into one binary.
  cmd/eventing-operator/main.go
  cmd/operator/kodata/knative-eventing/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/2-upgrade-to-v0.14.1.yaml
  cmd/operator/kodata/knative-serving/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/4-net-istio.yaml
  cmd/operator/main.go
  config/operator.yaml
  config/role.yaml
  config/role_binding.yaml
  config/service_account.yaml
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/upgrade.go
  pkg/reconciler/upgrade_test.go
  test/config/serving
  version/version_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#29 Consolidate transformers for common CRD fields, registry and config
  pkg/reconciler/common/config_maps.go
  pkg/reconciler/common/config_maps_test.go
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/extensions_test.go
  pkg/reconciler/common/images.go
  pkg/reconciler/common/images_test.go
  pkg/reconciler/common/testing/util.go
  pkg/reconciler/knativeeventing/common/defaultbroker.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
  pkg/reconciler/knativeeventing/common/extensions.go
  pkg/reconciler/knativeeventing/common/images.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/common/certs_test.go
  pkg/reconciler/knativeserving/common/config_maps.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/ha_test.go
  pkg/reconciler/knativeserving/common/images_test.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XXL

#33 Don't rely on in-reconciler state to determine last-in-cluster.
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#36 Move metrics reporting into its own event handler.
  pkg/reconciler/knativeserving/common/stats_reporter.go
  pkg/reconciler/knativeserving/common/stats_reporter_test.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/M

#39 Remove unnecessary KnativeServing code and finishing touches.
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#40 Make the prefix of the ConfigMap name optional in the CR
  pkg/reconciler/common/config_maps.go
  pkg/reconciler/common/config_maps_test.go
Labels: approved, cla: yes, lgtm, size/M

#24 Refreshing the docs
  README-eventing-operator.md
  README-serving-operator.md
  README.md
  config/300-eventing.yaml
  config/300-serving.yaml
  doc/upgrade_guide.md
  docs/configuration.md
  docs/development.md
  docs/installation.md
Labels: approved, cla: yes, lgtm, size/XXL

#43 Remove unused and deprecated code.
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeserving/controller.go
Labels: approved, cla: yes, lgtm, size/S

#46 Fix malformed license headers.
  test/client/setup.go
  test/clients.go
  test/e2e/knativeeventingdeployment_test.go
  test/e2e/knativeservingdeployment_test.go
  test/resources/verify.go
  test/upgrade/knativeeventingpreupgrade_test.go
  test/upgrade/knativeeventingupgrade_test.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/M

#34 Collect logs from spawned pods in CI.
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#45 Remove some unused test files.
  test/e2e-travis.sh
  test/test.sh
Labels: approved, cla: yes, lgtm, size/M

#42 Densen up unit test definitions.
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
  pkg/reconciler/knativeserving/common/certs_test.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/ha_test.go
  pkg/reconciler/knativeserving/common/resources_test.go
Labels: approved, cla: yes, lgtm, size/XL

#48 Own Markus
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#50 Update codegen
  Gopkg.lock
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
Labels: approved, cla: yes, lgtm, size/XS

#53 Hook up platform in the eventing operator.
  pkg/reconciler/knativeeventing/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#55 Simplify deleteObsoleteResources using common helpers.
  pkg/reconciler/common/unstructured.go
  pkg/reconciler/common/unstructured_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#51 Add the resources field to the eventing CRD
  config/300-eventing.yaml
  docs/configuration.md
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/resources.go
  pkg/reconciler/common/resources_test.go
  pkg/reconciler/common/testdata/manifest.yaml
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/M

#49 Eliminate the wasteful updates due to the aggregated rules
  pkg/reconciler/knativeserving/common/aggregated_rules.go
  pkg/reconciler/knativeserving/common/aggregated_rules_test.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L
