Repository knative/operator, pull requests merged in 2020-09, with the labels that each got.

#265 Add 0.17.3 eventing and 0.17.2 serving manifests
  cmd/operator/kodata/knative-eventing/0.17.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.17.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.17.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.17.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.17.2/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.2/5-serving-post-install-jobs.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#266 Skip the version checking for network ingress deployment
  test/resources/knativeresources.go
Labels: approved, cla: yes, lgtm, size/S

#267 [release-0.17] Add 0.17.3 eventing and 0.17.2 serving manifests
  cmd/operator/kodata/knative-eventing/0.17.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/6-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.17.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.17.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.17.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.17.2/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.2/5-serving-post-install-jobs.yaml
Labels: approved, cla: yes, size/XXL

#202 Docs for publishing the operator in OperatorHub
  docs/operatorhub.md
Labels: approved, cla: yes, lgtm, size/M

#258 Add the CSV 0.16 for operatorhub.io
  deploy/olm-catalog/knative-operator/0.16.0/knative-operator.v0.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-operator/0.16.0/knativeeventings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.16.0/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/knative-operator.package.yaml
Labels: approved, cla: yes, lgtm, size/XL

#268 [master] Format markdown
  docs/operatorhub.md
Labels: approved, cla: yes, lgtm, size/M

#272 Remove 'master' terminology where possible.
  docs/configuration.md
  docs/operatorhub.md
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/knativeeventing_preupgrade_test.go
Labels: approved, cla: yes, lgtm, size/XS

#273 Add linting config and fix issues.
  .golangci.yaml
  pkg/reconciler/common/releases.go
Labels: approved, cla: yes, lgtm, size/S

#271 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#274 Set E2E_UPGRADE_TESTS_SERVING_USE to test kservice in eventing tests
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#278 Transform jobs first so images are overridable.
  pkg/reconciler/common/transformers.go
Labels: approved, cla: yes, lgtm, size/XS

#285 Add sugar controller 0.16
  cmd/operator/kodata/knative-eventing/0.16.0/3-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.16.0/4-eventing-post-install-jobs.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/3-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/4-eventing-post-install-jobs.yaml
Labels: approved, cla: yes, size/L

#283 [Automated] Update actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#286 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#287 [Automated] Fix misspellings
  cmd/operator/kodata/knative-eventing/0.14.0/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.14.1/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.14.2/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.0/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.1/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.2/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.3/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.15.4/1-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.16.0/2-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.16.1/2-eventing.yaml
  cmd/operator/kodata/knative-eventing/0.17.0/3-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/2-eventing-core.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/M
