Repository knative/operator, pull requests merged in 2021-04, with the labels that each got.

#540 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/resources/doc.go
  vendor/knative.dev/serving/pkg/resources/endpoints.go
  vendor/knative.dev/serving/pkg/resources/pods.go
  vendor/knative.dev/serving/pkg/resources/scale.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#532 Refactor the cache mechanism
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/stages.go
  pkg/reconciler/common/testdata/kodata/empty/empty-resource.yaml
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#541 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/M

#542 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#543 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/M

#547 Delete the installed ingress resources only
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XS

#548 [release-0.22] Delete the installed ingress resources only
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XS

#552 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/0.22/net-istio.yaml
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#551 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#553 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#554 Update the configuration for 0.23 development
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#555 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/state.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/state.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/autoscalerconfig.go
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#558 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#559 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/0.20.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#560 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_lifecycle.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#562 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
