Repository knative/operator, pull requests merged in 2021-09, with the labels that each got.

#747 Allow to set Tolerations via `spec.deployments.tolerations`
  config/300-eventing.yaml
  config/300-serving.yaml
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/deployments_override.go
  pkg/reconciler/common/deployments_override_test.go
Labels: approved, lgtm, cla: yes, size/L

#746 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/serving/test/upgrade/upgrade.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#753 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/0.23/net-contour.yaml
  cmd/operator/kodata/ingress/0.24/net-contour.yaml
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#754 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#752 [release-0.25] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.24/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.25/kafka/source.yaml
  cmd/operator/kodata/ingress/0.23/net-contour.yaml
  cmd/operator/kodata/ingress/0.24/net-contour.yaml
  cmd/operator/kodata/ingress/0.25/net-contour.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#743 Add the lables: app.kubernetes.io/version and app.kubernetes.io/part-of
  config/300-eventing.yaml
  config/300-serving.yaml
  config/config-logging.yaml
  config/config-observability.yaml
  config/operator.yaml
  config/role.yaml
  config/role_binding.yaml
  config/service_account.yaml
Labels: approved, lgtm, cla: yes, size/M

#758 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/upgrade/upgrade.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#759 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.23/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.24/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.24/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/ingress/0.24/net-istio.yaml
  cmd/operator/kodata/ingress/0.25/net-istio.yaml
  cmd/operator/kodata/knative-eventing/0.22.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.22.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.22.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.22.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.22.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.22.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/0.22.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.22.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.22.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.22.3/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.25.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.25.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.25.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.25.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#738 Prepare the Knative Operator for the label app.kubernetes.io/version
  hack/generate-yamls.sh
Labels: approved, lgtm, cla: yes, size/XS

#760 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/0.22/net-contour.yaml
  cmd/operator/kodata/ingress/0.22/net-istio.yaml
  cmd/operator/kodata/knative-eventing/0.23.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.23.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.23.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.23.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.23.5/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.23.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.24.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.24.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.24.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.24.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.24.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.24.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.25.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.25.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.25.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.25.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.25.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.25.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/0.23.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.23.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.23.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.23.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.24.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.24.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.24.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.24.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/serving/test/upgrade/upgrade.go
  vendor/knative.dev/serving/test/v1/route.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#761 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.22/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.22/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.22/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.22/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/0.23/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.23/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.23/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/0.24/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.24/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.25/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.25/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.25/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.25/rabbitmq/rabbitmq-source.yaml
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/state.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/state.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/XL

#764 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/state.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#765 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#766 [release-0.25] Remove pingsource from HA scaling (#740)
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, cla: yes, size/XS

#750 Fix the error issue with installing spec.manifests
  pkg/reconciler/common/releases.go
  pkg/reconciler/knativeeventing/source/source.go
  pkg/reconciler/knativeeventing/source/source_test.go
  pkg/reconciler/knativeserving/ingress/ingress.go
  pkg/reconciler/knativeserving/ingress/ingress_test.go
Labels: approved, lgtm, cla: yes, size/L

#769 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/serving/test/v1/revision.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#748 Adjust maxReplicas in HPA when high-availability has larger number
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, cla: yes, size/M

#772 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.25/kafka/source.yaml
  cmd/operator/kodata/ingress/0.23/net-istio.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#774 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, cla: yes, size/S

#775 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/S

#776 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#777 Add the support of `spec.deployments.affinity`
  config/300-eventing.yaml
  config/300-serving.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/deployments_override.go
  pkg/reconciler/common/deployments_override_test.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/test/v1/route.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#778 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, cla: yes, size/S

#779 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, cla: yes, size/S

#780 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/S

#781 fix misspelling wih -> with
  pkg/reconciler/knativeeventing/source/source_test.go
Labels: approved, lgtm, cla: yes, size/XS, ok-to-test

#782 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#783 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.22/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.22/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.22/github/github.yaml
  cmd/operator/kodata/eventing-source/0.22/prometheus/prometheus-source.yaml
  cmd/operator/kodata/eventing-source/0.22/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/0.23/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.23/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.23/github/github.yaml
  cmd/operator/kodata/eventing-source/0.23/prometheus/prometheus-source.yaml
  cmd/operator/kodata/eventing-source/0.23/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/0.24/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.24/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.24/github/github.yaml
  cmd/operator/kodata/eventing-source/0.24/prometheus/prometheus-source.yaml
  cmd/operator/kodata/eventing-source/0.24/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/0.25/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.25/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.25/github/github.yaml
  cmd/operator/kodata/eventing-source/0.25/prometheus/prometheus-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/XL

#785 Prepare for the 0.26 release
  cmd/operator/kodata/eventing-source/0.26/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.26/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.26/github/github.yaml
  cmd/operator/kodata/eventing-source/0.26/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.26/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.26/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.26/prometheus/prometheus-source.yaml
  cmd/operator/kodata/eventing-source/0.26/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/0.26/redis/redis-source.yaml
  test/e2e-common.sh
Labels: approved, size/XXL, lgtm, cla: yes

#786 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, cla: yes, size/XS

#787 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, cla: yes, size/S

#749 Apply `high-availability` to all deployments managed by operator
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
  test/resources/verify.go
Labels: approved, lgtm, cla: yes, size/L, ok-to-test

#788 Remove pingsource-mt-adapter from the list of unsupported HA
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, cla: yes, size/S

#790 Adding COC, contributing doc
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
Labels: approved, lgtm, cla: yes, size/M, kind/documentation

#793 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.24/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.25/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.26/kafka/source.yaml
Labels: approved, lgtm, cla: yes, size/L

#795 [main] Update community files
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, cla: yes, size/S

#797 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M
