Repository knative/operator, pull requests merged in 2021-07, with the labels that each got.

#679 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/S

#680 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#685 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.22/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.24/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/0.22.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.22.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.22.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.22.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.22.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.22.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#684 Continue the 0.25 development
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#686 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#688 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#687 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/reconciler/route/config/store.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#689 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/buffered_write_syncer.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/typeparams/doc.go
  vendor/golang.org/x/tools/internal/typeparams/notypeparams.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams.go
  vendor/knative.dev/serving/test/README.md
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e_constants.go
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#694 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/metric.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/podautoscaler.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  vendor/knative.dev/serving/pkg/gc/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#695 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.24/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/0.23.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.23.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.23.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.23.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.23.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.23.4/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#697 Suggest to install istio for the gateway issue
  pkg/reconciler/common/install.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#698 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#700 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/0.24.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.24.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.24.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.24.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.24.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.24.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#702 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/README.md
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/conversion_error.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/doc.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/serving_client.go
  vendor/knative.dev/serving/test/clients.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#701 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#703 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#704 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#705 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
