Repository knative/operator, pull requests merged in 2021-03, with the labels that each got.

#493 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/reconciler/testing/clock.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/upgrade/probe.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#497 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#501 [master] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/0.21.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.21.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.21.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.21.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.21.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.21.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#502 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/listers.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#504 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/resource_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/channelable.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1beta1/listers.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_defaulter_test_helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#503 Add DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#513 Drop unnecessary occurrences of master
  .github/ISSUE_TEMPLATE/feature-request.md
  docs/development.md
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#496 Pin the target version to latest for master dev
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#514 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#516 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/networking/pkg/apis/networking/generic_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/test/README.md
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/knative.dev/serving/test/upgrade/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#515 [Automated] Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#517 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#500 Refactor the test cases of checking the resources
  pkg/reconciler/common/testing/util.go
  pkg/reconciler/knativeserving/ingress/ingress_test.go
Labels: approved, cla: yes, lgtm, size/L

#518 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/0.20.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.20.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.20.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.20.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.20.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.20.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.21.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.21.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.21.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.21.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.21.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.21.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#524 [Automated] Update actions
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#525 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#527 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#528 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/0.19.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.19.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.19.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.19.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.19.5/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#494 Update the development doc for operator
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#531 Allow the update of ingress resources with spec.additionalManifests
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XS

#533 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#529 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#530 [Automated] Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#534 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#535 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1beta1/broker/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/webhook/README.md
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#536 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#537 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#538 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#539 [release-0.21] Update the manifests for the branch release-0.21
  cmd/operator/kodata/knative-eventing/0.19.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.19.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.19.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.19.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.19.5/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.21.3/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
