Repository knative/operator, pull requests merged in 2021-08, with the labels that each got.

#707 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/upgrade/postupgrade.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#708 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#713 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#714 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/S

#716 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/S

#722 [main] Format Go code
  hack/tools.go
  test/downgrade/knative_postdowngrade_test.go
  test/e2e/knativeeventingdeployment_test.go
  test/e2e/knativeservingdeployment_test.go
  test/upgrade/upgrade_test.go
  test/upgrade/upgradeeventing_test.go
  test/upgrade/upgradeserving_test.go
Labels: approved, lgtm, cla: yes, size/XS

#727 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, cla: yes, size/XS

#728 Change the branch name for 0.25 tests
  test/e2e-common.sh
Labels: approved, lgtm, cla: yes, size/XS

#730 Drop version check for autoscaler HA
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, cla: yes, size/S

#729 Continue the 0.26 development
  test/e2e-common.sh
Labels: approved, lgtm, cla: yes, size/XS

#735 Drop deprecated `enabledComponents` field setting
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, cla: yes, size/M

#739 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#740 Remove pingsource from HA scaling
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, cla: yes, size/XS

#742 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.25/kafka/source.yaml
  cmd/operator/kodata/ingress/0.25/net-contour.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.24.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes
