Repository knative/operator, pull requests merged in 2021-01, with the labels that each got.

#416 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#418 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#419 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#423 Update attributes to describe which files are generated and/or vendored
  .gitattributes
Labels: approved, cla: yes, lgtm, size/XS

#394 Preserve the values of the environment variables for the pingsource-mt-adapter deploy resource
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform.go
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform_test.go
Labels: approved, cla: yes, lgtm, size/L

#425 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#426 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#429 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#430 Refactor the function getLatestRelease and add the correct error message
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/stages.go
Labels: approved, cla: yes, lgtm, size/L

#433 Add the post install job for eventing 0.20
  cmd/operator/kodata/knative-eventing/0.20.0/6-eventing-post-install.yaml
Labels: approved, cla: yes, lgtm, size/L

#432 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#436 [] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/operator/v1alpha1/knativeeventing/filtered/fake/fake.go
  pkg/client/injection/informers/operator/v1alpha1/knativeeventing/filtered/knativeeventing.go
  pkg/client/injection/informers/operator/v1alpha1/knativeserving/filtered/fake/fake.go
  pkg/client/injection/informers/operator/v1alpha1/knativeserving/filtered/knativeserving.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#438 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#443 Add `latest` as a special version supported by the operator
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/testdata/kodata/knative-eventing/latest/eventing-core.yaml
  pkg/reconciler/common/testdata/kodata/knative-eventing/latest/in-memory-channel.yaml
  pkg/reconciler/common/testdata/kodata/knative-serving/latest/serving-core.yaml
  pkg/reconciler/common/testdata/kodata/knative-serving/latest/serving-hpa.yaml
  test/resources/knativeresources.go
Labels: approved, cla: yes, lgtm, size/L

#446 Actually pin deps to 0.20 branches
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#439 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#437 Transition to the new upgrade framework for upgrade tests
  test/e2e-common.sh
  test/e2e-eventing-upgrade-tests.sh
  test/e2e-serving-upgrade-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e_flags.go
  test/upgrade/installation/shell.go
  test/upgrade/knativeeventing_postupgrade_test.go
  test/upgrade/knativeeventing_preupgrade_test.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
  test/upgrade/servingoperator_postupgrade_test.go
  test/upgrade/upgrade_test.go
  third_party/VENDOR-LICENSE/knative.dev/hack/shell/LICENSE
  vendor/knative.dev/hack/shell/executor.go
  vendor/knative.dev/hack/shell/fail-example.sh
  vendor/knative.dev/hack/shell/prefixer.go
  vendor/knative.dev/hack/shell/project.go
  vendor/knative.dev/hack/shell/types.go
  vendor/knative.dev/pkg/system/testing/names.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/knative.dev/pkg/test/upgrade/vars.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#448 Add the eventing 0.20.1
  cmd/operator/kodata/knative-eventing/0.20.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/6-eventing-post-install.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#449 [release-0.20] Add the eventing 0.20.1
  cmd/operator/kodata/knative-eventing/0.20.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.20.1/6-eventing-post-install.yaml
Labels: approved, cla: yes, lgtm, size/XXL
