Repository knative/operator, pull requests merged in 2021-12, with the labels that each got.

#886 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#888 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, cla: yes, size/XS

#887 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, cla: yes, size/XS

#889 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#891 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/upgrade/upgrade.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#890 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, cla: yes, size/XS

#892 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/README.md
  vendor/cloud.google.com/go/RELEASING.md
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/iam/credentials/apiv1/doc.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/iam_credentials_client.go
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/testing.md
  vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/module/pseudo.go
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/windows/mksyscall.go
  vendor/golang.org/x/sys/windows/setupapi_windows.go
  vendor/golang.org/x/sys/windows/setupapierrors_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/google.golang.org/api/iamcredentials/v1/iamcredentials-gen.go
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/k8s.io/gengo/args/args.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/generator.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/k8s.io/gengo/types/types.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#894 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#895 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.25/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.0/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.0.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.0.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.0.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.0.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.0.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.0.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#897 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#898 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#899 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#903 Remove unused field
  pkg/reconciler/common/job_test.go
Labels: approved, lgtm, size/XS

#904 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#906 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#907 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#909 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#910 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS
