Repository knative/operator, pull requests merged in 2021-10, with the labels that each got.

#799 Revert "Update community files (#795)"
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, cla: yes, size/S

#800 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/S

#801 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.24/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.25/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#805 [main] Revert "Remove pingsource-mt-adapter from the list of unsupported HA
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, cla: yes, size/S

#803 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/M

#806 Pass controller to extensions to be able to setup new handlers
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/extensions_test.go
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeserving/controller.go
Labels: approved, lgtm, cla: yes, size/S

#808 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, cla: yes, size/L

#810 [release-0.26] Update the manifests for 0.26
  cmd/operator/kodata/eventing-source/0.24/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.25/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.26/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.24.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.25.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.26.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#811 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.24/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.26/kafka/source.yaml
  cmd/operator/kodata/knative-serving/0.23.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.23.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.23.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.23.3/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, cla: yes

#809 Make network layer consistent throughout e2e-test
  test/resources/knativeserving.go
  test/resources/verify.go
Labels: approved, lgtm, cla: yes, size/M, ok-to-test
