Repository knative/operator, pull requests merged in 2021-05, with the labels that each got.

#574 Update the script of the upgrade tests for serving
  go.sum
  test/e2e-serving-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#577 Use deployment namespace to determine gateway namespace for Kourier
  pkg/reconciler/knativeserving/ingress/kourier.go
  pkg/reconciler/knativeserving/ingress/kourier_test.go
Labels: approved, cla: yes, lgtm, size/S

#575 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#584 [release-0.22] Update the dependencies for 0.22
  cmd/operator/kodata/ingress/0.22/net-istio.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.20.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.21.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.22.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#567 Clear OwnerReferences on knative-local-gateway Service
  pkg/reconciler/knativeserving/common/ingress_service.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#585 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#588 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#589 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#590 Set the namespace of the service knative-local-gateway to the istio namespace
  pkg/reconciler/knativeserving/common/ingress_service.go
  pkg/reconciler/knativeserving/common/ingress_service_test.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#591 Add pingsource-mt-adapter into HA list
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, cla: yes, lgtm, size/XS

#576 Return an actual newest version of the directory `latest` is not available
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/testdata/kodata-no-latest/knative-serving/0.16.0/serving-core.yaml
  pkg/reconciler/common/testdata/kodata-no-latest/knative-serving/0.16.0/serving-hpa.yaml
  pkg/reconciler/common/testdata/kodata-no-latest/knative-serving/0.16.1/serving-core.yaml
  pkg/reconciler/common/testdata/kodata-no-latest/knative-serving/0.16.1/serving-crd.yaml
  pkg/reconciler/common/testdata/kodata-no-latest/knative-serving/0.16.1/serving-hpa.yaml
  pkg/reconciler/knativeserving/ingress/ingress.go
  pkg/reconciler/knativeserving/ingress/ingress_test.go
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.19/kourier.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.19/net-contour.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.19/net-istio.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.20/kourier.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.20/net-contour.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.20/net-istio.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.21/kourier.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.21/net-contour.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.21/net-istio.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.22/kourier.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.22/net-contour.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress/0.22/net-istio.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/knative-serving/0.22.0/serving-core.yaml
  pkg/reconciler/knativeserving/ingress/testdata/kodata/knative-serving/latest/serving-core.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#594 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#592 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#598 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscribable_channelable_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#599 Pin the target version to latest for further development
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#600 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#617 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#613 Improve fetcher by supporting version parameter
  cmd/fetcher/main.go
  hack/update-codegen.sh
  pkg/packages/release.go
  pkg/packages/release_test.go
Labels: approved, cla: yes, lgtm, size/M

#625 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#627 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#624 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/sut/broker.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
