Repository knative/operator, pull requests merged in 2021-06, with the labels that each got.

#631 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#630 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#638 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/gopkg.in/evanphx/json-patch.v4/errors.go
  vendor/gopkg.in/evanphx/json-patch.v4/merge.go
  vendor/gopkg.in/evanphx/json-patch.v4/patch.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/knative.dev/serving/test/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#623 Add a 20-second timeout before running the post upgrade tests
  go.mod
  go.sum
  test/downgrade/knative_postdowngrade_test.go
  test/resources/knativeresources.go
  test/resources/verify.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
  test/upgrade/upgradeeventing_test.go
  vendor/knative.dev/serving/test/clients.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#640 [release-0.23] Update the manifests and dependencies
  cmd/operator/kodata/knative-eventing/0.23.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.23.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.23.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.23.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.23.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.23.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/0.20.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.20.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.20.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.20.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/0.22.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.22.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.22.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.22.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#641 Add the manifests of the eventing sources
  cmd/fetcher/kodata/config.yaml
  cmd/operator/kodata/eventing-source/0.20/awssqs/awssqs.yaml
  cmd/operator/kodata/eventing-source/0.20/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.20/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.20/github/github.yaml
  cmd/operator/kodata/eventing-source/0.20/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.20/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.20/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.20/prometheus/prometheus-source.yaml
  cmd/operator/kodata/eventing-source/0.20/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/0.20/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/0.21/awssqs/awssqs.yaml
  cmd/operator/kodata/eventing-source/0.21/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.21/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.21/github/github.yaml
  cmd/operator/kodata/eventing-source/0.21/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.21/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.21/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.21/prometheus/prometheus-source.yaml
  cmd/operator/kodata/eventing-source/0.21/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/0.21/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/0.22/awssqs/awssqs.yaml
  cmd/operator/kodata/eventing-source/0.22/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.22/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.22/github/github.yaml
  cmd/operator/kodata/eventing-source/0.22/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.22/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.22/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.22/prometheus/prometheus-source.yaml
  cmd/operator/kodata/eventing-source/0.22/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/0.22/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/0.23/awssqs/awssqs.yaml
  cmd/operator/kodata/eventing-source/0.23/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/0.23/couchdb/couchdb.yaml
  cmd/operator/kodata/eventing-source/0.23/github/github.yaml
  cmd/operator/kodata/eventing-source/0.23/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.23/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.23/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.23/prometheus/prometheus-source.yaml
  cmd/operator/kodata/eventing-source/0.23/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/0.23/redis/redis-source.yaml
  pkg/packages/config.go
  pkg/packages/release.go
Labels: approved, cla: yes, lgtm, size/XXL

#643 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#642 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#644 Change the APIs for eventing sources
  config/300-eventing.yaml
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#648 Update Knative dependency for release-0.23
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#647 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#649 Add $KO_FLAGS to e2e test
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#650 Make e2e test run over other networks
  test/e2e-common.sh
  test/e2e-tests.sh
  test/resources/knativeserving.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#645 Add the logic to install sources
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeeventing/source/source.go
  pkg/reconciler/knativeeventing/source/source_test.go
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/awssqs/awssqs.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/ceph/ceph.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/couchdb/couchdb.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/github/github.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/gitlab/gitlab.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/kafka/source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/natss/eventing-natss.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/prometheus/prometheus-source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/rabbitmq/rabbitmq-source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/redis/redis-source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/awssqs/awssqs.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/ceph/ceph.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/couchdb/couchdb.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/github/github.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/gitlab/gitlab.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/kafka/source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/natss/eventing-natss.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/prometheus/prometheus-source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/rabbitmq/rabbitmq-source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/redis/redis-source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/empty.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/knative-eventing/0.22.1/1-eventing-crds.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/knative-eventing/0.22.1/2-eventing-core.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/knative-eventing/0.23.0/1-eventing-crds.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/knative-eventing/0.23.0/2-eventing-core.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#651 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#653 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.22/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.23/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/0.23/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/ingress/0.23/net-istio.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/listers.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/scheme/scheme.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_single_event_helper.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#657 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#656 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/eventing/test/lib/resources/serving.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#655 drop use of pkg/test.KubeClient
  test/clients.go
Labels: approved, cla: yes, lgtm, size/XS

#660 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#658 Allow to set NodeSelector via `spec.deployments.nodeSelector`
  config/300-eventing.yaml
  config/300-serving.yaml
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/deployments_override.go
  pkg/reconciler/common/deployments_override_test.go
Labels: approved, cla: yes, lgtm, size/M

#663 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#654 Remove the Amazon SQS source
  cmd/fetcher/kodata/config.yaml
  cmd/operator/kodata/eventing-source/0.20/awssqs/awssqs.yaml
  cmd/operator/kodata/eventing-source/0.21/awssqs/awssqs.yaml
  cmd/operator/kodata/eventing-source/0.22/awssqs/awssqs.yaml
  cmd/operator/kodata/eventing-source/0.23/awssqs/awssqs.yaml
  config/300-eventing.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#661 Allocate the array with a smaller initial size
  pkg/reconciler/knativeeventing/source/source.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#664 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#665 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.23/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.23/kafka/source.yaml
  cmd/operator/kodata/eventing-source/0.23/natss/eventing-natss.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#666 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/0.23.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.23.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.23.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.23.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/storage/names/generate.go
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/knative.dev/eventing/test/flags/eventing_environment.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#667 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#668 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#669 gracefully handle net-* deployment rename
  pkg/reconciler/common/ha.go
  pkg/reconciler/knativeserving/ingress/kourier.go
  pkg/reconciler/knativeserving/ingress/kourier_test.go
Labels: approved, cla: yes, lgtm, size/S

#670 [release-0.23] Update the manifests and dependencies for 0.23
  cmd/operator/kodata/ingress/0.23/net-istio.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.23.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/0.23.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.23.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.23.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.23.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#672 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#674 Install the webhooks after installing the deployments and services
  cmd/operator/kodata/eventing-source/0.23/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/0.23.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.23.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.23.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.23.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.23.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.23.3/6-eventing-post-install.yaml
  go.mod
  go.sum
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/api_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/feature/store.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#677 Update the manifests for the release-0.24
  cmd/operator/kodata/eventing-source/0.24/github/github.yaml
  cmd/operator/kodata/eventing-source/0.24/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/0.24/redis/redis-source.yaml
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL
