Repository knative/operator, pull requests merged in 2021-02, with the labels that each got.

#451 Allow to specify build platform for test images
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#312 Add ingress configuration support
  cmd/operator/kodata/ingress/0.17/kourier.yaml
  cmd/operator/kodata/ingress/0.17/net-contour.yaml
  cmd/operator/kodata/ingress/0.17/net-istio.yaml
  cmd/operator/kodata/ingress/0.18/kourier.yaml
  cmd/operator/kodata/ingress/0.18/net-contour.yaml
  cmd/operator/kodata/ingress/0.18/net-istio.yaml
  cmd/operator/kodata/ingress/0.19/kourier.yaml
  cmd/operator/kodata/ingress/0.19/net-contour.yaml
  cmd/operator/kodata/ingress/0.19/net-istio.yaml
  cmd/operator/kodata/ingress/0.20/kourier.yaml
  cmd/operator/kodata/ingress/0.20/net-contour.yaml
  cmd/operator/kodata/ingress/0.20/net-istio.yaml
  config/300-serving.yaml
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/knativeserving/ingress/contour.go
  pkg/reconciler/knativeserving/ingress/contour_test.go
  pkg/reconciler/knativeserving/ingress/ingress.go
  pkg/reconciler/knativeserving/ingress/ingress_test.go
  pkg/reconciler/knativeserving/ingress/istio.go
  pkg/reconciler/knativeserving/ingress/istio_test.go
  pkg/reconciler/knativeserving/ingress/kourier.go
  pkg/reconciler/knativeserving/ingress/kourier_test.go
  pkg/reconciler/knativeserving/ingress/testdata/kodata/ingress
  pkg/reconciler/knativeserving/knativeserving.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
Labels: approved, cla: yes, lgtm, size/XXL

#455 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#453 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_validation.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/testing/v1/configuration.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/README.md
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/upload-test-images.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#456 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/go.opencensus.io/.travis.yml
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/go.opencensus.io/metric/metricexport/reader.go
  vendor/go.opencensus.io/trace/basetypes.go
  vendor/go.opencensus.io/trace/spanstore.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/go.opencensus.io/trace/trace_api.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/SECURITY.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_util.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/internal/grpcutil/target.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/resolver/config_selector.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/test/e2e/helpers/README.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#457 Looks like removing unused bits
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#458 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/eventing/test/e2e/helpers/README.md
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#445 [Automated] Fix misspellings
  cmd/operator/kodata/knative-eventing/0.17.0/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.17.9/2-eventing-core.yaml
Labels: approved, cla: yes, lgtm, size/M

#459 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/stats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#444 Add ha eventing master
  config/300-eventing.yaml
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#460 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#461 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#462 Align all used YAML modules
  go.mod
  pkg/packages/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#464 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#465 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#471 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#474 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#473 Remove 4-net-istio.yaml from 0.17 to 0.19 directory
  cmd/operator/kodata/knative-serving/0.17.0/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.1/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.2/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.3/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.17.4/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.18.0/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.18.1/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.18.2/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.18.3/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.19.0/4-net-istio.yaml
  cmd/operator/kodata/knative-serving/0.20.0/4-net-istio.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#476 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#469 Move istio gateway's override setting into spec.ingress.istio
  config/300-serving.yaml
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/ingress/istio.go
  pkg/reconciler/knativeserving/ingress/istio_test.go
Labels: approved, cla: yes, lgtm, size/L

#466 Update manifestival version to latest
  go.mod
  go.sum
  pkg/reconciler/common/install_test.go
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/go.mod
  vendor/github.com/imdario/mergo/go.sum
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/manifestival/client-go-client/.travis.yml
  vendor/github.com/manifestival/client-go-client/README.md
  vendor/github.com/manifestival/client-go-client/go.mod
  vendor/github.com/manifestival/client-go-client/go.sum
  vendor/github.com/manifestival/manifestival/.travis.yml
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/README.md
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/go.mod
  vendor/github.com/manifestival/manifestival/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
Labels: approved, cla: yes, lgtm, size/XXL

#478 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#479 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#467 CRD version api bump to v1
  config/300-eventing.yaml
  config/300-serving.yaml
Labels: approved, cla: yes, lgtm, size/XL

#468 Adds support for extension custom manifests
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/extensions_test.go
  pkg/reconciler/common/testdata/kodata/additional-manifests/additional-sa.yaml
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#481 [RELEASE-0.20] Add support for custom manifests
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/extensions_test.go
  pkg/reconciler/common/testdata/kodata/additional-manifests/additional-sa.yaml
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, cla: yes, lgtm, size/M

#480 Add HA support for autoscaler
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, cla: yes, lgtm, size/M

#472 Support spec.deployments to override configuration of system deployments
  config/300-eventing.yaml
  config/300-serving.yaml
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/deployments_override.go
  pkg/reconciler/common/deployments_override_test.go
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/transformers.go
Labels: approved, cla: yes, lgtm, size/L

#483 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#484 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#487 [master] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/0.20.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.20.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.20.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.20.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#492 Download the ingress net-istio into the correct directory
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S
