Repository knative/operator, pull requests merged in 2022-01, with the labels that each got.

#913 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#917 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/0.26/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.0/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.1/kafka/source.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#922 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#919 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#921 Add flags to direct fetcher input and output
  cmd/fetcher/main.go
  pkg/packages/release.go
Labels: approved, lgtm, size/M

#927 Fix the base directory issue for the fetcher and update deps & manifests
  cmd/fetcher/main.go
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/shell/project.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/serving/test/upgrade/postdowngrade.go
  vendor/knative.dev/serving/test/upgrade/postupgrade.go
  vendor/knative.dev/serving/test/upgrade/preupgrade.go
  vendor/knative.dev/serving/test/upgrade/upgrade.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#893 Add the support of resources configuration based on deploy and container names
  config/300-eventing.yaml
  config/300-serving.yaml
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/deployments_override.go
  pkg/reconciler/common/deployments_override_test.go
  pkg/reconciler/common/resources.go
  pkg/reconciler/common/resources_test.go
  pkg/reconciler/common/testdata/manifest.yaml
  pkg/reconciler/common/transformers.go
Labels: approved, lgtm, size/L

#928 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/0.26.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/0.26.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/0.26.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/0.26.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/0.26.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/0.26.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.1.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.1.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.1.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.1.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.1.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.1.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.1.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.1.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.1.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.1.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/shell/project.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#937 Add the Kafka eventing source for 1.2
  cmd/operator/kodata/eventing-source/1.2/kafka/source.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/shell/project.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#939 Resume the further development in terms of the tests
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#938 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#941 Refactor the common functions for the APIs for the API transition
  hack/update-codegen.sh
  pkg/apis/operator/base/common.go
  pkg/apis/operator/base/doc.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/config_maps.go
  pkg/reconciler/common/config_maps_test.go
  pkg/reconciler/common/deployments.go
  pkg/reconciler/common/deployments_override.go
  pkg/reconciler/common/deployments_override_test.go
  pkg/reconciler/common/deployments_test.go
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/extensions_test.go
  pkg/reconciler/common/finalizer.go
  pkg/reconciler/common/finalizer_test.go
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
  pkg/reconciler/common/images.go
  pkg/reconciler/common/images_test.go
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
  pkg/reconciler/common/job.go
  pkg/reconciler/common/job_test.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/resources.go
  pkg/reconciler/common/stages.go
  pkg/reconciler/common/stages_test.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeeventing/source/source.go
  pkg/reconciler/knativeeventing/source/source_test.go
  pkg/reconciler/knativeserving/common/ingress_service_test.go
  pkg/reconciler/knativeserving/ingress/ingress.go
  pkg/reconciler/knativeserving/ingress/ingress_test.go
  pkg/reconciler/knativeserving/knativeserving.go
  test/downgrade/knative_postdowngrade_test.go
  test/resources/knativeserving.go
  test/resources/verify.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
Labels: approved, lgtm, size/XL
