Repository knative/operator, pull requests merged in 2022-06, with the labels that each got.

#1085 Support overriding env vars per container
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/common.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/reconciler/common/deployments_override.go
  pkg/reconciler/common/deployments_override_test.go
  pkg/reconciler/common/env_override.go
Labels: approved, lgtm, size/XL

#1090 [release-1.4] Update the manifests and deps for 1.4
  cmd/operator/kodata/eventing-source/1.2/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.3/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.4/github/github.yaml
  cmd/operator/kodata/eventing-source/1.4/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/5-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1091 Add the ceph 1.5 eventing-source
  cmd/operator/kodata/eventing-source/1.5/ceph/ceph.yaml
Labels: approved, lgtm, size/XL

#1095 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1097 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1100 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1103 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.2.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1104 Remove the v1alpha1 in the CRDs
  cmd/webhook/main.go
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  config/webhook/webhook.yaml
  hack/update-codegen.sh
  pkg/apis/operator/v1alpha1/deploymentoverride.go
  pkg/apis/operator/v1alpha1/deploymentoverride_test.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/istioconfig.go
  pkg/apis/operator/v1alpha1/istioconfig_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_conversion.go
  pkg/apis/operator/v1alpha1/knativeeventing_conversion_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_types.go
  pkg/apis/operator/v1alpha1/knativeserving_conversion.go
  pkg/apis/operator/v1alpha1/knativeserving_conversion_test.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeserving_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/register_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/fake/fake_knativeeventing.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/fake/fake_knativeserving.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/fake/fake_operator_client.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/knativeeventing.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/knativeserving.go
  pkg/client/clientset/versioned/typed/operator/v1alpha1/operator_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/operator/interface.go
  pkg/client/informers/externalversions/operator/v1alpha1/interface.go
  pkg/client/informers/externalversions/operator/v1alpha1/knativeeventing.go
  pkg/client/informers/externalversions/operator/v1alpha1/knativeserving.go
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/operator/v1alpha1/knativeeventing/fake/fake.go
  pkg/client/injection/informers/operator/v1alpha1/knativeeventing/filtered/fake/fake.go
  pkg/client/injection/informers/operator/v1alpha1/knativeeventing/filtered/knativeeventing.go
  pkg/client/injection/informers/operator/v1alpha1/knativeeventing/knativeeventing.go
  pkg/client/injection/informers/operator/v1alpha1/knativeserving/fake/fake.go
  pkg/client/injection/informers/operator/v1alpha1/knativeserving/filtered/fake/fake.go
  pkg/client/injection/informers/operator/v1alpha1/knativeserving/filtered/knativeserving.go
  pkg/client/injection/informers/operator/v1alpha1/knativeserving/knativeserving.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/state.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/state.go
  pkg/client/listers/operator/v1alpha1/expansion_generated.go
  pkg/client/listers/operator/v1alpha1/knativeeventing.go
  pkg/client/listers/operator/v1alpha1/knativeserving.go
Labels: approved, size/XXL, lgtm

#1108 [release-1.5] Update the manifests
  cmd/operator/kodata/eventing-source/1.5/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.1/5-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1109 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/types.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1110 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1112 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1114 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1113 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
