Repository knative/operator, pull requests merged in 2022-07, with the labels that each got.

#1117 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1118 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/generate-cert.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1119 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1120 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.5/rabbitmq/rabbitmq-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1123 Override the default broker class if it is defined in the spec.config
  pkg/reconciler/knativeeventing/common/defaultbroker.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
Labels: approved, lgtm, size/L

#1122 Remove the migration jobs and related RBAC
  config/post-install/migration_role.yaml
  config/post-install/migration_role_binding.yaml
  config/post-install/migration_service_account.yaml
  config/post-install/storage-version-migrator.yaml
  config/rbac/migration_role.yaml
  config/rbac/migration_role_binding.yaml
  config/rbac/migration_service_account.yaml
Labels: approved, lgtm, size/L

#1124 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1125 Implement minAvailable for PodDisruptionBudget
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/common.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/reconciler/common/poddisruptionbudget_override.go
  pkg/reconciler/common/poddisruptionbudget_override_test.go
  pkg/reconciler/common/testdata/manifest.yaml
  pkg/reconciler/common/transformers.go
Labels: approved, lgtm, size/L

#1121 Increase initialDelaySeconds to 120
  config/webhook/webhook.yaml
Labels: approved, lgtm, size/XS

#1126 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1128 Update the current version for the upgrade tests for 1.6 release
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1129 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1130 Resume the development after 1.6
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1132 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.5/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/5-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1134 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1135 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1136 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/language/common.go
  vendor/golang.org/x/text/internal/language/compact.go
  vendor/golang.org/x/text/internal/language/compact/compact.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/compact/parents.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/compact/tags.go
  vendor/golang.org/x/text/internal/language/compose.go
  vendor/golang.org/x/text/internal/language/coverage.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/match.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/language/tags.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tag/tag.go
  vendor/golang.org/x/text/language/coverage.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/go1_1.go
  vendor/golang.org/x/text/language/go1_2.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/language/tags.go
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/pool/doc.go
  vendor/knative.dev/pkg/pool/interface.go
  vendor/knative.dev/pkg/pool/pool.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/serving/test/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1139 update knative.dev/hack
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1140 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1137 Prevent the case of an empty replicas in high-availability
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, size/S

#1141 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.5/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1143 Fix the issue when "webhookdefinitions" does not exist in CSV
  hack/generate-bundle.sh
Labels: approved, lgtm, size/S

#1145 Refactor the README to catch up the latest changes
  README.md
  docs/configuration.md
  docs/installation.md
  docs/upgrade.md
Labels: approved, lgtm, size/L

#1144 Remove the old manifests for operatorhub
  deploy/olm-catalog/knative-operator/0.15.1/knative-operator.v0.15.1.clusterserviceversion.yaml
  deploy/olm-catalog/knative-operator/0.15.1/knativeeventings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.15.1/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.15.2/knative-operator.v0.15.2.clusterserviceversion.yaml
  deploy/olm-catalog/knative-operator/0.15.2/knativeeventings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.15.2/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.15.3/knative-operator.v0.15.3.clusterserviceversion.yaml
  deploy/olm-catalog/knative-operator/0.15.3/knativeeventings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.15.3/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.16.0/knative-operator.v0.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-operator/0.16.0/knativeeventings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/0.16.0/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-operator/knative-operator.package.yaml
Labels: approved, size/XXL, lgtm

#1146 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1147 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1149 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/markdown-lint-config.rc
  vendor/knative.dev/eventing/test/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
