Repository knative/operator, pull requests merged in 2022-02, with the labels that each got.

#942 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#943 [main] Update actions
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
Labels: approved, lgtm, size/M

#947 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#949 Remove the flaky Continual tests for serving
  test/upgrade/upgradeserving_test.go
Labels: approved, lgtm, size/XS

#948 Add the conversion function for v1alpha1 and v1beta1
  pkg/apis/operator/v1alpha1/deploymentoverride.go
  pkg/apis/operator/v1alpha1/deploymentoverride_test.go
  pkg/apis/operator/v1alpha1/istioconfig.go
  pkg/apis/operator/v1alpha1/istioconfig_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_conversion.go
  pkg/apis/operator/v1alpha1/knativeeventing_conversion_test.go
  pkg/apis/operator/v1alpha1/knativeserving_conversion.go
  pkg/apis/operator/v1alpha1/knativeserving_conversion_test.go
  pkg/apis/operator/v1beta1/knativeeventing_conversion.go
  pkg/apis/operator/v1beta1/knativeeventing_conversion_test.go
  pkg/apis/operator/v1beta1/knativeserving_conversion.go
  pkg/apis/operator/v1beta1/knativeserving_conversion_test.go
Labels: approved, size/XXL, lgtm

#940 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/logger.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/knative.dev/serving/test/prober.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#951 Use default logger configuration
  test/upgrade/upgrade_test.go
Labels: approved, lgtm, size/S

#952 Change the logger configuration for the upgrade tests
  test/upgrade/upgradeeventing_test.go
  test/upgrade/upgradeserving_test.go
Labels: approved, lgtm, size/S

#936 Add conversion webhook module
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/refs
  cmd/webhook/main.go
  config/400-webhook-secret.yaml
  pkg/apis/operator/register.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/operator/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/register_test.go
  pkg/apis/operator/v1beta1/knativeeventing_lifecycle.go
  pkg/apis/operator/v1beta1/knativeeventing_lifecycle_test.go
  pkg/apis/operator/v1beta1/knativeserving_lifecycle.go
  pkg/apis/operator/v1beta1/knativeserving_lifecycle_test.go
  pkg/apis/operator/v1beta1/register.go
  pkg/apis/operator/v1beta1/register_test.go
  third_party/VENDOR-LICENSE/k8s.io/apiextensions-apiserver/pkg/LICENSE
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1beta1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/generic.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1beta1/expansion_generated.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/factory/factory.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#959 Remove the continual tests for serving upgrade
  test/upgrade/upgradeserving_test.go
Labels: approved, lgtm, size/XS

#958 Keep the default image name the same as the original
  pkg/reconciler/common/images.go
  pkg/reconciler/common/images_test.go
Labels: approved, lgtm, size/M

#956 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/serving/test/README.md
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#962 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/1.1.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.1.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.1.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.1.3/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.2.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#961 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#964 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/1.2.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#967 [release-1.2] Update the release-1.2 dependencies and manifests
  cmd/operator/kodata/knative-serving/1.1.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.1.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.1.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.1.3/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.2.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.1/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.2.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/logger.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#966 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#972 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#969 Promote v1beta1 as the storage version
  config/200-role.yaml
  config/201-service_account.yaml
  config/300-eventing.yaml
  config/300-serving.yaml
  config/service_account.yaml
  pkg/apis/operator/base/common.go
  pkg/apis/operator/v1alpha1/knativeeventing_conversion.go
  pkg/apis/operator/v1alpha1/knativeserving_conversion.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/stub/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/stub/reconciler.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/stub/controller.go
  pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/stub/reconciler.go
  pkg/reconciler/common/deployments_override_test.go
  pkg/reconciler/common/deployments_test.go
  pkg/reconciler/common/extensions_test.go
  pkg/reconciler/common/finalizer_test.go
  pkg/reconciler/common/ha_test.go
  pkg/reconciler/common/images_test.go
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
  pkg/reconciler/common/job.go
  pkg/reconciler/common/job_test.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/resources_test.go
  pkg/reconciler/common/stages_test.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/knativeeventing/common/defaultbroker.go
  pkg/reconciler/knativeeventing/common/defaultbroker_test.go
  pkg/reconciler/knativeeventing/common/sinkbindingselectionmode.go
  pkg/reconciler/knativeeventing/common/sinkbindingselectionmode_test.go
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeeventing/source/source.go
  pkg/reconciler/knativeeventing/source/source_test.go
  pkg/reconciler/knativeserving/common/certs.go
  pkg/reconciler/knativeserving/common/certs_test.go
  pkg/reconciler/knativeserving/common/ingress_service.go
  pkg/reconciler/knativeserving/common/ingress_service_test.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/ingress/contour.go
  pkg/reconciler/knativeserving/ingress/contour_test.go
  pkg/reconciler/knativeserving/ingress/ingress.go
  pkg/reconciler/knativeserving/ingress/ingress_test.go
  pkg/reconciler/knativeserving/ingress/istio.go
  pkg/reconciler/knativeserving/ingress/istio_test.go
  pkg/reconciler/knativeserving/ingress/kourier.go
  pkg/reconciler/knativeserving/ingress/kourier_test.go
  pkg/reconciler/knativeserving/knativeserving.go
  test/clients.go
  test/downgrade/knative_postdowngrade_test.go
  test/e2e-common.sh
  test/resources/knativeeventing.go
  test/resources/knativeserving.go
  test/resources/verify.go
  test/upgrade/postdowngrade.go
  test/upgrade/postupgrade.go
  test/upgrade/preupgrade.go
Labels: approved, size/XXL, lgtm

#974 Fix the issue with alpha and beta transition
  pkg/apis/operator/v1alpha1/istioconfig.go
  pkg/apis/operator/v1alpha1/istioconfig_test.go
  pkg/apis/operator/v1alpha1/knativeeventing_conversion.go
  pkg/apis/operator/v1alpha1/knativeserving_conversion.go
  pkg/apis/operator/v1alpha1/knativeserving_conversion_test.go
  test/e2e-common.sh
Labels: approved, lgtm, size/L

#977 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#973 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS

#978 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#982 [release-1.2] Update the dependencies of branch release-1.2
  cmd/operator/kodata/knative-serving/0.26.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/0.26.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/0.26.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/0.26.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.0.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.0.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.0.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.0.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#980 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#976 Add the post install yaml into the release
  hack/generate-yamls.sh
Labels: approved, lgtm, size/S

#983 Add the conversion path into the CRDs
  config/300-eventing.yaml
  config/300-serving.yaml
Labels: approved, lgtm, size/XS

#984 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/1.1.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.1.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.1.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.1.4/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
