Repository knative/operator, pull requests merged in 2022-11, with the labels that each got.

#1273 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/rabbitmq/rabbitmq-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1275 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1283 Update go version and dependencies
  cmd/operator/main.go
  go.mod
  go.sum
  hack/boilerplate/boilerplate.sh.txt
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/packages/config.go
  pkg/packages/config_test.go
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/images_test.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/testing/util.go
  pkg/reconciler/knativeeventing/source/source.go
  pkg/reconciler/knativeserving/common/certs_test.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1282 [release-1.8] Add the RBAC for kafka eventing source
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/5-eventing-post-install.yaml
  cmd/operator/main.go
  config/rbac/role.yaml
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/packages/config.go
  pkg/packages/config_test.go
  pkg/reconciler/common/extensions.go
  pkg/reconciler/common/images_test.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/testing/util.go
  pkg/reconciler/knativeeventing/source/source.go
  pkg/reconciler/knativeserving/common/certs_test.go
Labels: approved, size/XXL, lgtm

#1276 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1272 Change the script to generate the bundle
  hack/generate-bundle.sh
Labels: approved, lgtm, size/XS

#1280 Fix the RBAC issue for kafka eventing source
  config/rbac/role.yaml
Labels: approved, lgtm, size/L

#1287 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.7.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.5/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.8.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.1/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1288 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1289 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1291 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1292 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-serving/1.5.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.5.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.5.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.5.1/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.6.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.6.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.6.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.6.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.7.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.7.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.7.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.7.3/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.8.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
