Repository knative/operator, pull requests merged in 2022-05, with the labels that each got.

#1057 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1050 Add the configuration of selector for services
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/common.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/reconciler/common/services_override.go
  pkg/reconciler/common/services_override_test.go
Labels: approved, lgtm, size/M, ok-to-test

#1058 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.2.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1059 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1060 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1061 Update the template and samples for csv bundle
  config/manifests/bases/knative-operator.clusterserviceversion.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_knativeeventing.yaml
  config/samples/operator_v1alpha1_knativeserving.yaml
Labels: approved, lgtm, size/M

#1064 [release-1.4] Update the manifests and deps
  cmd/operator/kodata/knative-eventing/1.2.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1066 Add the annotation sidecar.istio.io/inject: "false" to operator-webhook
  config/webhook/webhook.yaml
Labels: approved, lgtm, size/XS

#1070 Added a retry mechanism to update the KnativeServing CR in the integration tests
  test/resources/verify.go
Labels: approved, lgtm, size/S

#1071 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1072 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1073 Replace the default namespace with operators for operatorhub submission
  hack/generate-bundle.sh
Labels: approved, lgtm, size/XS

#1074 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/prober.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1075 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.2/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.3/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.4/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.4.1/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1076 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1077 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/utils/internal/third_party/forked/golang/golang-lru/lru.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/config/doc.go
  vendor/knative.dev/networking/pkg/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/networking/pkg/labels/labels.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1081 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS, skip-review

#1082 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M
