Repository knative/operator, pull requests merged in 2022-08, with the labels that each got.

#1150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1151 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1152 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1153 [release-1.5] Add the migration task in the reconciler to upgrade existing CRs
  cmd/operator/kodata/eventing-source/1.5/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.5/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/5-eventing-post-install.yaml
  config/rbac/role.yaml
  go.mod
  hack/update-codegen.sh
  pkg/reconciler/common/migrate.go
  pkg/reconciler/knativeeventing/controller.go
  pkg/reconciler/knativeserving/controller.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1154 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/v1/revision.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1156 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1160 Tolerate the case that the existing eventing version is not found
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, lgtm, size/XS

#1159 Resolve the server-side CRD conflicts by adding a dummy webhook
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  config/webhook/webhook.yaml
Labels: approved, lgtm, size/S

#1161 Fix rabbitmq permission
  config/rbac/role.yaml
Labels: approved, lgtm, size/M

#1168 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1167 [release-1.6] Update codeverify
  cmd/operator/kodata/eventing-source/1.5/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.2/5-eventing-post-install.yaml
  hack/update-codegen.sh
Labels: approved, size/XXL, lgtm

#1169 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/configuration.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1174 Add the version as the paramater for the fetcher
  hack/update-codegen.sh
Labels: approved, lgtm, size/XS

#1177 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1178 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS, skip-review

#1179 Change the order of resources and revert the webhook changes
  config/000-webhook-secret.yaml
  config/001-webhook.yaml
  config/002-webhook-service.yaml
  config/100-eventing.yaml
  config/100-serving.yaml
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  config/webhook/webhook.yaml
Labels: approved, lgtm, size/S

#1181 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1182 Add the webhook for future CRD future conversion
  cmd/operator/kodata/knative-eventing/1.5.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.3/5-eventing-post-install.yaml
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  config/webhook/webhook.yaml
Labels: approved, size/XXL, lgtm

#1183 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1176 Remove the disabled ingresses
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm, size/XS

#1175 Remove the sources if they are disabled
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeeventing/source/source.go
  pkg/reconciler/knativeeventing/source/source_test.go
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/awssqs/awssqs.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/couchdb/couchdb.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.22/prometheus/prometheus-source.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/awssqs/awssqs.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/couchdb/couchdb.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/eventing-source/0.23/prometheus/prometheus-source.yaml
Labels: approved, size/XXL, lgtm

#1185 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1187 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1188 Revert breaking change from PR 1176
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm, size/XS

#1189 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1190 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/tracing.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/forwarder/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/receiver/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/operations.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1191 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.3/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.3/github/github.yaml
  cmd/operator/kodata/eventing-source/1.3/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.3/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.3/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.3/redis/redis-source.yaml
  cmd/operator/kodata/knative-eventing/1.3.0/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.0/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.0/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.7.0/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.0/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.0/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.0/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.0/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1193 Prepare 1.7 release and update the deps and manifests
  cmd/operator/kodata/eventing-source/1.7/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.7/github/github.yaml
  cmd/operator/kodata/eventing-source/1.7/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.7/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.7/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.7/kourier.yaml
  cmd/operator/kodata/ingress/1.7/net-contour.yaml
  cmd/operator/kodata/ingress/1.7/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.7.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.1/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.3.0/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.3.0/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.3.0/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.3.0/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.3.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.3.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.3.1/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.3.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.7.0/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.7.0/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.7.0/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.7.0/4-serving-post-install-jobs.yaml
  hack/update-codegen.sh
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/testdata/invalid_kodata/knative-serving/0.26.0_unmatched_version/serving-core.yaml
  pkg/reconciler/common/testdata/invalid_kodata/knative-serving/0.26.0_unmatched_version/serving-hpa.yaml
  test/e2e-common.sh
  test/e2e/knativeservingdeployment_test.go
  test/resources/knativeserving.go
Labels: approved, size/XXL, lgtm

#1195 Add 1.7.1 serving manifests and revert the changes regarding revision-timeout-seconds
  cmd/operator/kodata/knative-serving/1.7.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.7.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.7.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.7.1/4-serving-post-install-jobs.yaml
  test/e2e/knativeservingdeployment_test.go
  test/resources/knativeserving.go
Labels: approved, size/XXL, lgtm

#1196 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
