Repository knative/operator, pull requests merged in 2022-09, with the labels that each got.

#1197 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1198 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.6/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.7/rabbitmq/rabbitmq-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/broker_prefer_reply_header_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_prefer_reply_header_helper.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1199 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1201 Do not change `spec.replicas` directory for the Deployment which has HPA
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
Labels: approved, lgtm, size/S

#1203 [release-1.7] Update the manifests for 1.7
  cmd/operator/kodata/eventing-source/1.6/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.7/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.5.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.4/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.6.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.6.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.6.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.6.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.6.1/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.7.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.2/5-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1204 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1205 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1207 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/broker_redelivery_helper.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1208 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/operator/v1beta1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1beta1/knativeserving/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1209 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1210 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1215 [release-1.4] Add the version to the fetcher
  cmd/operator/kodata/eventing-source/1.3/natss/eventing-natss.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.4.2/5-eventing-post-install.yaml
  hack/update-codegen.sh
Labels: approved, size/XXL, lgtm

#1226 Running the './hack/update-codegen.sh' script
  cmd/operator/kodata/knative-eventing/1.5.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.6.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.6.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.6.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.6.1/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.7.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.7.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.7.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.7.2/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1220 [release-1.3] Add the version to the fetcher
  .github/workflows/knative-style.yaml
  cmd/operator/kodata/eventing-source/1.2/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.3/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.3/natss/eventing-natss.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.2.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.5/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.3.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.3.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.3.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.3.2/4-serving-post-install-jobs.yaml
  hack/update-codegen.sh
Labels: approved, size/XXL, lgtm

#1227 Allow to use custom bootstrap configmap for Kourier
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/ingressconfiguration.go
  pkg/reconciler/knativeserving/ingress/ingress_test.go
  pkg/reconciler/knativeserving/ingress/kourier.go
  pkg/reconciler/knativeserving/ingress/kourier_test.go
Labels: approved, lgtm, size/L
