Repository knative/operator, pull requests merged in 2022-10, with the labels that each got.

#1229 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1230 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1228 Add the code to safeguard the nil pointer issue
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm, size/XS

#1231 Refactor the ingress service for istio
  pkg/reconciler/knativeserving/ingress/ingress_service.go
  pkg/reconciler/knativeserving/ingress/ingress_service_test.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm, size/L

#1233 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1235 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1236 Update the deps and manifests
  go.mod
  go.sum
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_config_set.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserialization_options.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserializer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/error_strategy.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/lexer_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/ll1_analyzer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/recognizer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/semantic_context.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/tree.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils_set.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/README.md
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParser.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParserLexer.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_base_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_lexer.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_parser.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_visitor.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/reactor.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1239 [release-1.7] Update the fetcher to pick the correct kafka sources
  cmd/fetcher/kodata/config.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.5/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.6.2/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.3/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.6.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.6.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.6.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.6.1/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.7.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.7.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.7.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.7.2/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1242 Update the fetcher and manfests for kafka sources
  cmd/fetcher/kodata/config.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/source.yaml
Labels: approved, size/XXL, lgtm

#1249 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/pelletier/go-toml/v2/.gitattributes
  vendor/github.com/pelletier/go-toml/v2/.gitignore
  vendor/github.com/pelletier/go-toml/v2/.golangci.toml
  vendor/github.com/pelletier/go-toml/v2/.goreleaser.yaml
  vendor/github.com/pelletier/go-toml/v2/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/v2/Dockerfile
  vendor/github.com/pelletier/go-toml/v2/LICENSE
  vendor/github.com/pelletier/go-toml/v2/README.md
  vendor/github.com/pelletier/go-toml/v2/SECURITY.md
  vendor/github.com/pelletier/go-toml/v2/ci.sh
  vendor/github.com/pelletier/go-toml/v2/decode.go
  vendor/github.com/pelletier/go-toml/v2/errors.go
  vendor/github.com/pelletier/go-toml/v2/internal/ast/ast.go
  vendor/github.com/pelletier/go-toml/v2/internal/ast/builder.go
  vendor/github.com/pelletier/go-toml/v2/internal/ast/kind.go
  vendor/github.com/pelletier/go-toml/v2/internal/danger/danger.go
  vendor/github.com/pelletier/go-toml/v2/internal/danger/typeid.go
  vendor/github.com/pelletier/go-toml/v2/internal/tracker/key.go
  vendor/github.com/pelletier/go-toml/v2/internal/tracker/seen.go
  vendor/github.com/pelletier/go-toml/v2/localtime.go
  vendor/github.com/pelletier/go-toml/v2/marshaler.go
  vendor/github.com/pelletier/go-toml/v2/parser.go
  vendor/github.com/pelletier/go-toml/v2/scanner.go
  vendor/github.com/pelletier/go-toml/v2/strict.go
  vendor/github.com/pelletier/go-toml/v2/targets.go
  vendor/github.com/pelletier/go-toml/v2/types.go
  vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
  vendor/github.com/pelletier/go-toml/v2/utf8.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/reader.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1250 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#1251 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.5.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.5.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.5.6/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.5.6/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.5.6/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.7.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.4/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1247 Support deployments/workloads probe overrides
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/common.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/reconciler/common/probe_override.go
  pkg/reconciler/common/probe_override_test.go
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, lgtm, size/XL

#1263 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1264 Resume the development for 1.9
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1265 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1266 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.6/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.7/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.6.3/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1267 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1269 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1271 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1270 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
