Repository knative/operator, pull requests merged in 2022-04, with the labels that each got.

#1016 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#1015 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/XL

#1020 Fix tracing issues
  test/e2e-common.sh
  test/e2e-eventing-upgrade-tests.sh
Labels: approved, lgtm, size/M

#1022 Update the deps and manifests
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/sugar/filters.go
  vendor/knative.dev/eventing/pkg/reconciler/sugar/labels.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/sugar_helper.go
  vendor/knative.dev/eventing/test/upgrade/README.md
  vendor/knative.dev/eventing/test/upgrade/prober/config.toml
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/tracing.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1027 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1029 Change int32 into *int32 for Replicas
  pkg/apis/operator/base/common.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/deploymentoverride_test.go
  pkg/reconciler/common/deployments_override.go
  pkg/reconciler/common/deployments_override_test.go
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
  test/e2e-common.sh
  test/resources/verify.go
Labels: approved, lgtm, size/M

#1026 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/traces.go
  vendor/knative.dev/eventing/test/conformance/helpers/tracing/zipkin.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/pkg/networking/util.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1024 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, lgtm, size/L

#1030 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1036 [release-1.3] Update the manifests
  cmd/operator/kodata/eventing-source/1.0/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.1/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.2/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.2/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.2.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.3.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.3.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.3.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.3.1/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1031 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/1.2.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.3.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.3.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.3.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.3.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/errors.go
  vendor/github.com/golang-jwt/jwt/v4/map_claims.go
  vendor/github.com/golang-jwt/jwt/v4/parser_option.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/github.com/golang-jwt/jwt/v4/types.go
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/google.golang.org/api/googleapi/googleapi.go
  vendor/google.golang.org/api/iamcredentials/v1/iamcredentials-gen.go
  vendor/google.golang.org/api/internal/gensupport/resumable.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/common/interfaces.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
  vendor/sigs.k8s.io/json/go.mod
  vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go
  vendor/sigs.k8s.io/json/internal/golang/encoding/json/kubernetes_patch.go
Labels: approved, size/XXL, lgtm

#1037 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#1039 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/generate-cert.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1038 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, lgtm, size/XS

#1040 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/eventing/test/upgrade/upgrade.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1041 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/1.2.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.5/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.3.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.3.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.3.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.3.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/github.com/prometheus/procfs/Makefile
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/cmdline.go
  vendor/github.com/prometheus/procfs/doc.go
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/netstat.go
  vendor/github.com/prometheus/procfs/proc_cgroup.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/procfs/zoneinfo.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1043 Prepare for the 1.4 release
  test/e2e-common.sh
  test/resources/knativeresources.go
Labels: approved, lgtm, size/S

#1045 Continue to develop operator
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1051 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1052 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1053 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1055 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M
