Repository knative/operator, pull requests merged in 2022-03, with the labels that each got.

#985 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.0/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.0.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.0.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.0.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.0.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.0.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.0.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.2.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.2.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.2.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.2.3/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_386.go
  vendor/golang.org/x/sys/unix/syscall_linux_alarm.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_mipsx.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/syscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#986 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#987 Refactor the manifests under config/ to accommodate the operatorhub release
  PROJECT
  README.md
  config/200-role.yaml
  config/200-service_account.yaml
  config/201-role_binding.yaml
  config/202-webhook_role.yaml
  config/202-webhook_service_account.yaml
  config/203-webhook_role_binding.yaml
  config/300-eventing.yaml
  config/300-serving.yaml
  config/400-webhook-secret.yaml
  config/401-webhook.yaml
  config/402-webhook-service.yaml
  config/config-logging.yaml
  config/config-observability.yaml
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/config-logging-configmap.yaml
  config/manager/config-observability-configmap.yaml
  config/manager/kustomization.yaml
  config/manager/operator.yaml
  config/manifests/bases/knative-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/operator.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/rbac/webhook_role.yaml
  config/rbac/webhook_role_binding.yaml
  config/rbac/webhook_service_account.yaml
  config/samples/kustomization.yaml
  config/samples/namespaces.yaml
  config/samples/operator_v1alpha1_knativeeventing.yaml
  config/samples/operator_v1alpha1_knativeserving.yaml
  config/samples/operator_v1beta1_knativeeventing.yaml
  config/samples/operator_v1beta1_knativeserving.yaml
  config/scorecard/bases/config.yaml
  config/scorecard/kustomization.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  config/webhook/kustomization.yaml
  config/webhook/webhook-secret.yaml
  config/webhook/webhook-service.yaml
  config/webhook/webhook.yaml
  docs/operatorhub.md
  docs/release.md
  hack/generate-bundle.sh
Labels: approved, size/XXL, lgtm

#989 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.1.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.1.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.1.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.1.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.1.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.1.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/metric.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/podautoscaler.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/serving_client.go
  vendor/knative.dev/serving/pkg/gc/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#991 Update the deps and manifests for release-1.3
  cmd/operator/kodata/eventing-source/1.3/github/github.yaml
  cmd/operator/kodata/eventing-source/1.3/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.3/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.3/natss/eventing-natss.yaml
  cmd/operator/kodata/eventing-source/1.3/redis/redis-source.yaml
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#996 Refactor the post-install yaml files for API migration
  config/post-install/migration_role.yaml
  config/post-install/migration_role_binding.yaml
  config/post-install/migration_service_account.yaml
  config/post-install/storage-version-migrator.yaml
  config/rbac/kustomization.yaml
  config/rbac/migration_role.yaml
  config/rbac/migration_role_binding.yaml
  config/rbac/migration_service_account.yaml
  config/rbac/webhook_role_binding.yaml
  hack/generate-bundle.sh
Labels: approved, lgtm, size/M

#998 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.3/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.3/rabbitmq/rabbitmq-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#999 [release-1.3] Update the ceph and rabbitmq sources for release-1.3
  cmd/operator/kodata/eventing-source/1.3/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.3/rabbitmq/rabbitmq-source.yaml
  config/manifests/bases/knative-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#997 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1000 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.0/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.1/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.2/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.2/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.0.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.1.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1001 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1002 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#1003 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, size/M

#1005 Change the version to resume the development
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1010 Fix the RBAC issue for Knative due to the label change
  cmd/operator/kodata/eventing-source/1.0/kafka/source.yaml
  cmd/operator/kodata/eventing-source/1.1/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.0.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.1.4/6-eventing-post-install.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  go.mod
  go.sum
  test/clients.go
  test/resources/knativeserving.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1011 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1012 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.2.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.2.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/5-eventing-sugar-controller.yaml
  cmd/operator/kodata/knative-eventing/1.3.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/eventing/test/upgrade/prober/config.toml
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/knative.dev/eventing/test/upgrade/prober/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/client/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/defaults.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/structure.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/tracing.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/forwarder/operations.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/forwarder/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/receiver/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/operations.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/types.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1014 Set capability to Seamless Upgrades
  config/manifests/bases/knative-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#1013 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
