Repository knative/operator, pull requests merged in 2023-04, with the labels that each got.

#1392 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1393 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-serving/1.8.6/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.6/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.6/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.6/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.9.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.9.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.9.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.9.3/4-serving-post-install-jobs.yaml
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, size/XXL, lgtm

#1381 Allow to change webhook secret name via WEBHOOK_SECRET_NAME
  config/webhook/webhook.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#1396 [release-1.9] Patch another release for 1.9
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-serving/1.8.6/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.6/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.6/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.6/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.9.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.9.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.9.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.9.3/4-serving-post-install-jobs.yaml
  test/e2e-common.sh
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, size/XXL, lgtm

#1395 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1398 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#1399 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1401 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.8/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/1.9/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.9/github/github.yaml
  cmd/operator/kodata/eventing-source/1.9/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.9/redis/redis-source.yaml
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, lgtm, size/L

#1403 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1407 Correct the name of the license title
  config/webhook/webhook-secret.yaml
Labels: approved, lgtm, size/XS

#1410 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1412 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1417 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1413 Add the image overriding support for StatefulSet
  pkg/reconciler/common/images.go
  pkg/reconciler/common/images_test.go
Labels: approved, lgtm, size/M

#1415 Added the ingress and source paths into the status.manifests
  pkg/reconciler/common/install.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeeventing/source/source.go
  pkg/reconciler/knativeeventing/source/source_test.go
  pkg/reconciler/knativeserving/ingress/ingress.go
  pkg/reconciler/knativeserving/ingress/ingress_test.go
  pkg/reconciler/knativeserving/knativeserving.go
  pkg/reconciler/manifests/install.go
  pkg/reconciler/manifests/install_test.go
  pkg/reconciler/manifests/testdata/kodata/eventing-source/0.23/ceph/ceph.yaml
  pkg/reconciler/manifests/testdata/kodata/eventing-source/0.23/github/github.yaml
  pkg/reconciler/manifests/testdata/kodata/eventing-source/0.23/gitlab/gitlab.yaml
  pkg/reconciler/manifests/testdata/kodata/eventing-source/0.23/kafka/source.yaml
  pkg/reconciler/manifests/testdata/kodata/eventing-source/0.23/rabbitmq/rabbitmq-source.yaml
  pkg/reconciler/manifests/testdata/kodata/eventing-source/0.23/redis/redis-source.yaml
  pkg/reconciler/manifests/testdata/kodata/ingress/1.9/contour/net-contour.yaml
  pkg/reconciler/manifests/testdata/kodata/ingress/1.9/istio/net-istio.yaml
  pkg/reconciler/manifests/testdata/kodata/ingress/1.9/kourier/kourier.yaml
  pkg/reconciler/manifests/testdata/kodata/knative-eventing/0.23.0/1-eventing-crds.yaml
  pkg/reconciler/manifests/testdata/kodata/knative-eventing/0.23.0/2-eventing-core.yaml
  pkg/reconciler/manifests/testdata/kodata/knative-serving/1.9.0/serving-core.yaml
Labels: approved, size/XXL, lgtm

#1418 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1375 Update the year for the license boilerplates
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.sh.txt
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/apis/operator/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/doc.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/fake/fake_knativeeventing.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/fake/fake_knativeserving.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/fake/fake_operator_client.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/knativeeventing.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/knativeserving.go
  pkg/client/clientset/versioned/typed/operator/v1beta1/operator_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/operator/interface.go
  pkg/client/informers/externalversions/operator/v1beta1/interface.go
  pkg/client/informers/externalversions/operator/v1beta1/knativeeventing.go
  pkg/client/informers/externalversions/operator/v1beta1/knativeserving.go
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  pkg/client/injection/informers/factory/factory.go
  pkg/client/injection/informers/factory/fake/fake.go
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/operator/v1beta1/knativeeventing/fake/fake.go
  pkg/client/injection/informers/operator/v1beta1/knativeeventing/filtered/fake/fake.go
  pkg/client/injection/informers/operator/v1beta1/knativeeventing/filtered/knativeeventing.go
  pkg/client/injection/informers/operator/v1beta1/knativeeventing/knativeeventing.go
  pkg/client/injection/informers/operator/v1beta1/knativeserving/fake/fake.go
  pkg/client/injection/informers/operator/v1beta1/knativeserving/filtered/fake/fake.go
  pkg/client/injection/informers/operator/v1beta1/knativeserving/filtered/knativeserving.go
  pkg/client/injection/informers/operator/v1beta1/knativeserving/knativeserving.go
  pkg/client/injection/reconciler/operator/v1beta1/knativeeventing/controller.go
  pkg/client/injection/reconciler/operator/v1beta1/knativeeventing/reconciler.go
  pkg/client/injection/reconciler/operator/v1beta1/knativeeventing/state.go
  pkg/client/injection/reconciler/operator/v1beta1/knativeserving/controller.go
  pkg/client/injection/reconciler/operator/v1beta1/knativeserving/reconciler.go
  pkg/client/injection/reconciler/operator/v1beta1/knativeserving/state.go
  pkg/client/listers/operator/v1beta1/expansion_generated.go
  pkg/client/listers/operator/v1beta1/knativeeventing.go
  pkg/client/listers/operator/v1beta1/knativeserving.go
Labels: approved, lgtm, size/XS

#1424 Update the manifests for the 1.10 release
  cmd/operator/kodata/eventing-source/1.10/github/github.yaml
  cmd/operator/kodata/eventing-source/1.10/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.10/redis/redis-source.yaml
Labels: approved, size/XXL, lgtm

#1397 Fixed the installation issue of istio in prows
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#1426 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1427 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1425 Resume the development for 1.11
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1429 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1beta2/eventtype.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1beta2/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta2/eventtype.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta2/expansion_generated.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
