Repository knative/operator, pull requests merged in 2023-11, with the labels that each got.

#1622 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1623 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/1.12/kourier/kourier.yaml
  cmd/operator/kodata/knative-serving/1.11.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.4/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/iam/CHANGES.md
  vendor/cloud.google.com/go/iam/apiv1/iampb/iam_policy.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/options.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/policy.pb.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/credentialspb/common.pb.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/credentialspb/iamcredentials.pb.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/doc.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/iam_credentials_client.go
  vendor/cloud.google.com/go/iam/internal/version.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/bucket.go
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/hmac.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/doc.go
  vendor/cloud.google.com/go/storage/internal/apiv2/gapic_metadata.json
  vendor/cloud.google.com/go/storage/internal/apiv2/storage_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storagepb/storage.pb.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/invoke.go
  vendor/cloud.google.com/go/storage/reader.go
  vendor/github.com/gorilla/websocket/.editorconfig
  vendor/github.com/gorilla/websocket/.gitignore
  vendor/github.com/gorilla/websocket/.golangci.yml
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/Makefile
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/tls_handshake.go
  vendor/github.com/gorilla/websocket/tls_handshake_116.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/google.golang.org/api/internal/version.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1625 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1629 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/parallel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/sequence.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1631 Make SECURITY.md consistent
  SECURITY.md
Labels: approved, lgtm, size/XS

#1630 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/types.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/sender/services.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1639 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/github/github.yaml
  cmd/operator/kodata/eventing-source/1.11/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.12/github/github.yaml
  cmd/operator/kodata/eventing-source/1.12/gitlab/gitlab.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.12.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.11.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.5/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.12.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.12.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.12.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.12.1/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.12.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.12.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.12.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.12.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/version.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/containersource.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_helpers.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/test/e2e-external-domain-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1637 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1644 [release-1.11] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/github/github.yaml
  cmd/operator/kodata/eventing-source/1.11/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/ingress/1.10/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.10/kourier/kourier.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.7/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.10.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.5/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.10.6/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.6/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.6/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.6/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.11.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.11.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.5/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
