Repository knative/operator, pull requests merged in 2023-02, with the labels that each got.

#1332 [release-1.9] Update the manifests for branch 1.9
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/5-eventing-post-install.yaml
  config/manifests/bases/knative-operator.clusterserviceversion.yaml
  hack/generate-bundle.sh
Labels: approved, size/XXL, lgtm

#1334 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.1/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.2/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.9.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.3/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/pkg/utils/secret.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_chain_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/channel_dls_test_helper.go
  vendor/knative.dev/hack/shell/executor.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1333 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/M, skip-review

#1335 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.9.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.4/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1336 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1337 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.7.8/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.8/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.8/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.8/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.8.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.6/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.6/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.6/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.9.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.5/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1278 Fixing typo on actual API to use
  pkg/apis/operator/base/common.go
Labels: approved, lgtm, size/XS

#1340 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1341 Add 3scale-kourier-gateway to hasHorizontalPodAutoscaler
  pkg/reconciler/common/ha.go
Labels: approved, lgtm, size/XS

#1352 [release-1.9] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1351 [release-1.8] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#1354 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1356 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/1.8/kourier.yaml
  cmd/operator/kodata/ingress/1.8/net-contour.yaml
  cmd/operator/kodata/ingress/1.8/net-istio.yaml
  cmd/operator/kodata/ingress/1.9/kourier.yaml
  cmd/operator/kodata/ingress/1.9/net-contour.yaml
  cmd/operator/kodata/ingress/1.9/net-istio.yaml
  cmd/operator/kodata/knative-serving/1.8.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.9.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.9.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.9.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.9.1/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1357 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.9/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/ingress/1.8/kourier.yaml
  cmd/operator/kodata/ingress/1.8/net-contour.yaml
  cmd/operator/kodata/ingress/1.9/kourier.yaml
  cmd/operator/kodata/ingress/1.9/net-contour.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.9.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.9.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.9.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.9.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/broker_event_transformation_test_helper.go
  vendor/knative.dev/eventing/test/e2e/helpers/broker_test_helper.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
