Repository knative/operator, pull requests merged in 2023-06, with the labels that each got.

#1459 Add the retry mechanism for the resource verification
  test/resources/verify.go
Labels: approved, lgtm, size/S

#1461 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventtype.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1463 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/apiserversouce.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1467 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1466 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/channel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/secret.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/unstructured.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1468 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.9/istio/net-istio.yaml
  cmd/operator/kodata/knative-serving/1.10.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.9.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.9.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.9.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.9.4/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_defaults.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1470 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventtype.go
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/knative.dev/eventing/test/upgrade/prober/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/options.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1475 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventtype.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1476 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventtype.go
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1478 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1481 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1483 Mark operator-webhook as safe-to-evict via annotation value
  config/webhook/webhook.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#1485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1484 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1486 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
