Repository knative/operator, pull requests merged in 2023-12, with the labels that each got.

#1645 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1651 [release-1.10] Update istio gateway from v1alpha3 to v1beta1 (#1628)
  cmd/operator/kodata/eventing-source/1.10/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.10/github/github.yaml
  cmd/operator/kodata/eventing-source/1.10/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.10/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.10/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.10/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.10/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.10.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.5/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.10.6/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.6/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.6/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.6/4-serving-post-install-jobs.yaml
  pkg/apis/operator/base/ingressconfiguration.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/reconciler/knativeserving/ingress/istio.go
  pkg/reconciler/knativeserving/ingress/istio_test.go
Labels: approved, size/XXL, lgtm

#1650 [release-1.11] Update istio gateway from v1alpha3 to v1beta1 (#1628)
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/6-eventing-post-install.yaml
  pkg/apis/operator/base/ingressconfiguration.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/reconciler/knativeserving/ingress/istio.go
  pkg/reconciler/knativeserving/ingress/istio_test.go
Labels: approved, size/XXL, lgtm

#1654 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/1.12/kourier/kourier.yaml
Labels: approved, lgtm, size/S
