Repository knative/operator, pull requests merged in 2023-09, with the labels that each got.

#1549 [release-1.11] Update the eventing sources for 1.11
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/rabbitmq/rabbitmq-source.yaml
Labels: approved, lgtm, size/L

#1550 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1551 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.11.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1552 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1554 Fixed the image overriding issue for Jobs
  pkg/reconciler/common/images.go
  pkg/reconciler/common/images_test.go
  pkg/reconciler/common/transformers.go
Labels: approved, lgtm, size/S

#1556 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1343 Add Kourier LoadBalancerIP Config
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/ingressconfiguration.go
  pkg/reconciler/knativeserving/ingress/kourier.go
  pkg/reconciler/knativeserving/ingress/kourier_test.go
Labels: approved, lgtm, size/L, ok-to-test

#1558 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/serving/AUTHORS
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1559 [release-1.11] Fixed the image overriding issue for Jobs
  cmd/operator/kodata/eventing-source/1.11/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/5-eventing-post-install.yaml
  pkg/reconciler/common/images.go
  pkg/reconciler/common/images_test.go
  pkg/reconciler/common/transformers.go
Labels: approved, size/XXL, lgtm

#1548 set HPA replica values when workload overrides are set
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
  pkg/reconciler/common/hpa.go
  pkg/reconciler/common/hpa_test.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, lgtm, size/L

#1561 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1562 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1563 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1564 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/benbjohnson/clock/LICENSE
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/doc.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/storage.go
  vendor/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/README.md
  vendor/github.com/benbjohnson/clock/clock.go
  vendor/github.com/benbjohnson/clock/context.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/array.go
  vendor/go.uber.org/zap/array_go118.go
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/error.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/internal/stacktrace/stack.go
  vendor/go.uber.org/zap/internal/ztest/clock.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sink.go
  vendor/go.uber.org/zap/writer.go
  vendor/go.uber.org/zap/zapcore/core.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/lazy_with.go
  vendor/google.golang.org/api/internal/creds.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/grpc/dial_appengine.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/api/transport/http/dial_appengine.go
  vendor/google.golang.org/appengine/internal/socket/socket_service.pb.go
  vendor/google.golang.org/appengine/internal/socket/socket_service.proto
  vendor/google.golang.org/appengine/socket/doc.go
  vendor/google.golang.org/appengine/socket/socket_classic.go
  vendor/google.golang.org/appengine/socket/socket_vm.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1565 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.10.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.3/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.11.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1567 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1566 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1568 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1569 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/s2a.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/option/internaloption/internaloption.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1570 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/github.com/googleapis/enterprise-certificate-proxy/client/client.go
  vendor/github.com/googleapis/enterprise-certificate-proxy/client/util/util.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1572 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
