Repository knative/operator, pull requests merged in 2023-03, with the labels that each got.

#1358 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/1.8/net-istio.yaml
  cmd/operator/kodata/ingress/1.9/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.8.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.5/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1359 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1361 [release-1.9] Update the release manifests for 1.9
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.9/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/ingress/1.8/kourier.yaml
  cmd/operator/kodata/ingress/1.8/net-contour.yaml
  cmd/operator/kodata/ingress/1.8/net-istio.yaml
  cmd/operator/kodata/ingress/1.9/kourier.yaml
  cmd/operator/kodata/ingress/1.9/net-contour.yaml
  cmd/operator/kodata/ingress/1.9/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.6/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.8.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.8.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.5/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.9.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.9.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.9.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.9.1/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.9.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.9.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.9.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.9.2/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm, ok-to-test

#1364 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1368 Change the configuration to download Kafka source
  cmd/fetcher/kodata/config.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/5-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1369 [release-1.9] Change the configuration for kafka source
  cmd/fetcher/kodata/config.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/source.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.9.7/5-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1370 [release-1.8] Update the manifests for release 1.8
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.8/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/ingress/1.8/kourier.yaml
  cmd/operator/kodata/ingress/1.8/net-contour.yaml
  cmd/operator/kodata/ingress/1.8/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.7/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.8/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.8.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.8.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.8.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.8.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.8.5/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1363 Allow to set HostNetwork via `spec.deployments.hostNetwork`
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  go.mod
  pkg/apis/operator/base/common.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, lgtm, size/L, ok-to-test

#1372 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1376 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1374 [release-1.7] Fix the RBAC issue for kafka eventing source
  config/rbac/role.yaml
Labels: approved, lgtm, size/L

#1377 Add certs secret name read from env
  cmd/webhook/main.go
Labels: approved, lgtm, size/XS, ok-to-test

#1378 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/README.md
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1379 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1384 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1383 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#1386 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1388 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1390 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M
