Repository knative/operator, pull requests merged in 2023-08, with the labels that each got.

#1516 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#1521 Rename sandbox to extensions
  pkg/packages/config_test.go
  pkg/reconciler/knativeserving/ingress/istio.go
Labels: approved, lgtm, size/XS

#1520 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/eventing/test/upgrade/prober/configuration.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1519 Allow to disable probe
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, lgtm, size/S

#1522 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1526 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1515 Resume the development for 1.12
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1514 [release-1.11] Update the manifests for release-1.11
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.10/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.9/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/5-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1528 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_loong64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1529 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1531 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1532 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1534 Add more env vars for pingsource adapter env var preservation
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform.go
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform_test.go
Labels: approved, lgtm, size/S

#1536 Cherry pick 1534 to release 1.11
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/5-eventing-post-install.yaml
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform.go
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform_test.go
Labels: approved, size/XXL, lgtm

#1539 Cherry pick 1534 to release 1.10
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.10/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.9/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/5-eventing-post-install.yaml
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform.go
  pkg/reconciler/knativeeventing/common/replicasenvvarstransform_test.go
Labels: approved, size/XXL, lgtm

#1542 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1543 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1544 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e_flags.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1541 Added Ports to NodePort service-types in knative-serving
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/ingressconfiguration.go
  pkg/reconciler/knativeserving/ingress/kourier.go
  pkg/reconciler/knativeserving/ingress/kourier_test.go
Labels: approved, lgtm, size/L, ok-to-test

#1547 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/openzipkin/zipkin-go/.golangci.yml
  vendor/github.com/openzipkin/zipkin-go/README.md
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
