Repository knative/operator, pull requests merged in 2023-01, with the labels that each got.

#1303 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.7.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.7.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.7.7/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.7.7/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.7.7/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.8.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.4/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1308 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/deployment.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1309 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1310 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1311 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/abuse_protection.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1312 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/benbjohnson/clock/LICENSE
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/logger.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1313 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e/helpers/broker_channel_flow_helper.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#1314 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1316 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1317 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/serving/test/e2e-internal-encryption-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1301 Add the module to install and configure the security guard
  cmd/fetcher/kodata/config.yaml
  cmd/fetcher/main.go
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.8/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.8.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.8.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.8.5/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.8.5/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.8.5/5-eventing-post-install.yaml
  cmd/operator/kodata/security-guard/0.1/guard-service.yaml
  cmd/operator/kodata/security-guard/0.1/queue-proxy.yaml
  cmd/operator/kodata/security-guard/0.2/gate-account.yaml
  cmd/operator/kodata/security-guard/0.2/guard-service.yaml
  cmd/operator/kodata/security-guard/0.2/guardian-crd.yaml
  cmd/operator/kodata/security-guard/0.2/queue-proxy.yaml
  cmd/operator/kodata/security-guard/0.2/service-account.yaml
  cmd/operator/kodata/security-guard/0.3/gate-account.yaml
  cmd/operator/kodata/security-guard/0.3/guard-service.yaml
  cmd/operator/kodata/security-guard/0.3/guardian-crd.yaml
  cmd/operator/kodata/security-guard/0.3/queue-proxy.yaml
  cmd/operator/kodata/security-guard/0.3/service-account.yaml
  cmd/operator/kodata/security-guard/0.4/gate-account.yaml
  cmd/operator/kodata/security-guard/0.4/guard-service.yaml
  cmd/operator/kodata/security-guard/0.4/guardian-crd.yaml
  cmd/operator/kodata/security-guard/0.4/queue-proxy.yaml
  cmd/operator/kodata/security-guard/0.4/service-account.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  config/rbac/role.yaml
  pkg/apis/operator/base/securityconfiguration.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/apis/operator/v1beta1/knativeserving_types.go
  pkg/apis/operator/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/knativeserving/knativeserving.go
  pkg/reconciler/knativeserving/security/security.go
  pkg/reconciler/knativeserving/security/security_test.go
  pkg/reconciler/knativeserving/security/securityguard.go
  pkg/reconciler/knativeserving/security/securityguard_test.go
  pkg/reconciler/knativeserving/security/testdata/kodata/knative-serving/1.8.0/serving-core.yaml
  pkg/reconciler/knativeserving/security/testdata/kodata/knative-serving/latest/serving-core.yaml
  pkg/reconciler/knativeserving/security/testdata/kodata/security-guard/0.4/gate-account.yaml
  pkg/reconciler/knativeserving/security/testdata/kodata/security-guard/0.4/guard-service.yaml
  pkg/reconciler/knativeserving/security/testdata/kodata/security-guard/0.4/guardian-crd.yaml
  pkg/reconciler/knativeserving/security/testdata/kodata/security-guard/0.4/queue-proxy.yaml
  pkg/reconciler/knativeserving/security/testdata/kodata/security-guard/0.4/service-account.yaml
Labels: approved, size/XXL, lgtm

#1318 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1305 Allow to set TopologySpreadConstraints via `spec.deployments.topologySpreadConstraints`
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/common.go
  pkg/apis/operator/base/zz_generated.deepcopy.go
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, lgtm, size/XL, ok-to-test

#1320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_defaults.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/upgrade/autoscaler.go
  vendor/knative.dev/serving/test/upgrade/probe.go
  vendor/knative.dev/serving/test/upgrade/upgrade.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1321 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/upgrade/autoscaler.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1322 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1323 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1324 Take workload overrides into account for setting `SINK_BINDING_SELECTION_MODE` env var
  pkg/apis/operator/v1beta1/knativeeventing_types.go
  pkg/reconciler/knativeeventing/common/sinkbindingselectionmode.go
  pkg/reconciler/knativeeventing/common/sinkbindingselectionmode_test.go
Labels: approved, lgtm, size/L

#1325 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/apiserversouce.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
