Repository knative/operator, pull requests merged in 2023-10, with the labels that each got.

#1576 [release-1.11] manual back-port of https://github.com/knative/operator/pull/1548
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.10.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.3/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.11.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.1/4-serving-post-install-jobs.yaml
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
  pkg/reconciler/common/hpa.go
  pkg/reconciler/common/hpa_test.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, size/XXL, lgtm

#1577 [release-1.10] manual back-port of https://github.com/knative/operator/pull/1548
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-serving/1.10.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.3/4-serving-post-install-jobs.yaml
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/ha_test.go
  pkg/reconciler/common/hpa.go
  pkg/reconciler/common/hpa_test.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, size/XXL, lgtm

#1580 Fix wrongly dropped transformer
  pkg/reconciler/common/transformers.go
Labels: approved, lgtm, size/XS

#1578 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/fake/fake_broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/fake/fake_trigger.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/fake/fake_parallel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/fake/fake_sequence.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_channel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_subscription.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1579 Drop autoscaling/v2beta1 and policy/v1beta1
  pkg/reconciler/common/hpa_test.go
  pkg/reconciler/common/poddisruptionbudget_override.go
  pkg/reconciler/common/poddisruptionbudget_override_test.go
  pkg/reconciler/common/testdata/manifest.yaml
  pkg/reconciler/common/workload_override_test.go
  pkg/reconciler/knativeeventing/source/testdata/kodata/knative-eventing/0.22.1/2-eventing-core.yaml
  pkg/reconciler/knativeeventing/source/testdata/kodata/knative-eventing/0.23.0/2-eventing-core.yaml
  pkg/reconciler/manifests/testdata/kodata/knative-eventing/0.23.0/2-eventing-core.yaml
Labels: approved, lgtm, size/L

#1584 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1582 Support Eventing TLS
  cmd/fetcher/kodata/config.yaml
  cmd/operator/kodata/knative-eventing/1.10.0/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.10.0/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.0/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.0/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.0/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.0/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.0/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.0/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.4/6-eventing-post-install.yaml
  config/rbac/role.yaml
  pkg/reconciler/knativeeventing/eventing_tls.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  test/e2e-common.sh
Labels: approved, size/XXL, lgtm

#1581 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-internal-encryption-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1590 Improve KnativeEventing finalization for TLS resources
  pkg/reconciler/knativeeventing/eventing_tls.go
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, lgtm, size/S

#1591 [release-1.11] Improve KnativeEventing finalization for TLS resources (#1590)
  pkg/reconciler/common/install.go
  pkg/reconciler/knativeeventing/eventing_tls.go
  pkg/reconciler/knativeeventing/knativeeventing.go
Labels: approved, lgtm, size/M

#1589 Improve manifest deletion error handling
  pkg/reconciler/common/install.go
Labels: approved, lgtm, size/XS

#1593 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1592 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1599 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1600 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/iam/CHANGES.md
  vendor/cloud.google.com/go/iam/apiv1/iampb/policy.pb.go
  vendor/cloud.google.com/go/iam/internal/version.go
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/apiserversouce.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1601 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.10/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.10/github/github.yaml
  cmd/operator/kodata/eventing-source/1.10/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.10/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.10/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/1.11/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.11/github/github.yaml
  cmd/operator/kodata/eventing-source/1.11/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.11/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.11/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.10/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.10/kourier/kourier.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.10.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.11.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1606 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/pingsource.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-external-domain-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1609 [release-1.10] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.10/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.10/github/github.yaml
  cmd/operator/kodata/eventing-source/1.10/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.10/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.10/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.10/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.10/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/5-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.10.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.4/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1608 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1607 [release-1.11] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.10/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.10/github/github.yaml
  cmd/operator/kodata/eventing-source/1.10/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.10/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.10/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/1.11/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.11/github/github.yaml
  cmd/operator/kodata/eventing-source/1.11/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.11/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.11/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.10/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.10/kourier/kourier.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.10.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.11.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1605 [release-1.11] Update the manifests for release 1.11
  cmd/operator/kodata/eventing-source/1.10/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.10/github/github.yaml
  cmd/operator/kodata/eventing-source/1.10/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.10/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.10/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/1.11/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.11/github/github.yaml
  cmd/operator/kodata/eventing-source/1.11/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.11/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.10/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.10/kourier/kourier.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.11.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.3/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1613 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#1615 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1616 Resume the development of 1.13 for operator
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1618 Have link to adopters form in issue/PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
  .github/pull-request-template.md
Labels: approved, lgtm, size/S

#1617 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.11/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/ingress/1.10/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.10/kourier/kourier.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/ingress/1.12/contour/net-contour.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.10.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.5/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/knative.dev/serving/test/v1/configuration.go
  vendor/knative.dev/serving/test/v1/revision.go
  vendor/knative.dev/serving/test/v1/route.go
  vendor/knative.dev/serving/test/v1/service.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
