Repository knative/operator, pull requests merged in 2023-07, with the labels that each got.

#1489 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1479 Enable the support of NodeSelectors and tolerations on Jobs
  pkg/reconciler/common/testdata/manifest.yaml
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, lgtm, size/L

#1452 Simplify the transformer for the installed resources
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm, size/M

#1490 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1491 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1495 [release-1.10] Update the manifests for operator 1.10
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.10/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.9/istio/net-istio.yaml
  cmd/operator/kodata/knative-serving/1.10.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.9.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.9.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.9.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.9.4/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1496 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1497 Correct the labels for all resources
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  config/manager/config-logging-configmap.yaml
  config/manager/config-observability-configmap.yaml
  config/manager/operator.yaml
  config/rbac/clusterrole_aggregated.yaml
  config/rbac/clusterrole_aggregated_binding.yaml
  config/rbac/fake_clusterrole_aggregated_binding.yaml
  config/rbac/fake_service_account.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/rbac/webhook_role.yaml
  config/rbac/webhook_role_binding.yaml
  config/rbac/webhook_service_account.yaml
  config/webhook/webhook-secret.yaml
  config/webhook/webhook-service.yaml
  config/webhook/webhook.yaml
  hack/generate-yamls.sh
Labels: approved, lgtm, size/L

#1447 Add the helm template and the instruction on how to release helm chart
  charts/knative-operator/Chart.yaml
  charts/knative-operator/templates/operator.yaml
  charts/knative-operator/values.yaml
  docs/release.md
  hack/generate-helm.sh
Labels: approved, size/XXL, lgtm

#1500 Update the manifestival to 0.7.2
  go.mod
  go.sum
  pkg/reconciler/common/testdata/kodata/additional-manifests/additional-sa.yaml
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/internal/sources/yaml.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1504 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.10.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.2/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1507 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1508 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.11/ceph/ceph.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1510 Fix cluster scope resources
  pkg/reconciler/common/transformers.go
Labels: approved, lgtm, size/S

#1501 Make the helm charts as a base template to scaffold the artifacts
  config/charts/knative-operator/Chart.yaml
  config/charts/knative-operator/templates/operator.yaml
  config/charts/knative-operator/values.yaml
  config/manager/operator.yaml
  config/webhook/webhook.yaml
  hack/generate-helm.sh
  hack/generate-yamls.sh
Labels: approved, lgtm, size/L
