Repository knative/operator, pull requests merged in 2023-05, with the labels that each got.

#1431 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1432 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1433 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1434 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/eventtype.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1435 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/eventingtls.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/channel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1436 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1437 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/1.10.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.10.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.10.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.10.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/pingsource.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1440 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1443 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventtype.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/listers.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1445 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/trigger.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1446 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  pkg/client/injection/informers/operator/v1beta1/knativeeventing/filtered/knativeeventing.go
  pkg/client/injection/informers/operator/v1beta1/knativeeventing/knativeeventing.go
  pkg/client/injection/informers/operator/v1beta1/knativeserving/filtered/knativeserving.go
  pkg/client/injection/informers/operator/v1beta1/knativeserving/knativeserving.go
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/language/common.go
  vendor/golang.org/x/text/internal/language/compact.go
  vendor/golang.org/x/text/internal/language/compact/compact.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/compact/parents.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/compact/tags.go
  vendor/golang.org/x/text/internal/language/compose.go
  vendor/golang.org/x/text/internal/language/coverage.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/match.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/language/tags.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tag/tag.go
  vendor/golang.org/x/text/language/coverage.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/language/tags.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1448 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1441 Leverage the status.manifests to delete the old resources
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/stages.go
  pkg/reconciler/common/stages_test.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm, size/M

#1450 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/broker.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1451 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/injection/informers/eventing/v1/broker/broker.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/unstructured.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1453 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1457 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1458 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.10/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.9/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/3-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/4-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.10.1/5-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
