Repository knative/operator, pull requests merged in 2024-03, with the labels that each got.

#1721 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1722 [release-1.12] Update the manifests for 1.12
  .codecov.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.12/istio/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1723 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/eventing/test/e2e-conformance-tests.sh
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/knative.dev/eventing/test/e2e-tests.sh
  vendor/knative.dev/eventing/test/e2e-upgrade-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1724 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.13.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/client.go
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storagepb/storage.pb.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/writer.go
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1727 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1731 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1736 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1738 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1729 Added "trust.cert-manager.io" into the ClusterRole
  config/rbac/role.yaml
Labels: approved, lgtm, size/S

#1744 [release-1.13] Updated the manifests
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.12/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.13/istio/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.13.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.13.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.13.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.13.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.13.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.13.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.13.3/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1746 [release-1.11] Updated the manifest
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.11.6/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.6/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.6/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.6/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1745 [release-1.12] Update the manifests
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.6/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1751 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1753 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/await.go
  vendor/knative.dev/eventing/test/lib/duck/resource_checks.go
  vendor/knative.dev/eventing/test/lib/duck/serving_checks.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/eventing/test/lib/tracker.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1752 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1754 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/trace/trace.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/doc.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storagepb/storage.pb.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/storage.go
  vendor/github.com/golang/protobuf/jsonpb/decode.go
  vendor/github.com/golang/protobuf/jsonpb/encode.go
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/google.golang.org/api/iamcredentials/v1/iamcredentials-api.json
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/google.golang.org/genproto/googleapis/api/tidyfix.go
  vendor/google.golang.org/genproto/internal/doc.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1755 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1757 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/googleapis/gax-go/v2/.release-please-manifest.json
  vendor/github.com/googleapis/gax-go/v2/CHANGES.md
  vendor/github.com/googleapis/gax-go/v2/internal/version.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1759 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1760 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
