Repository knative/operator, pull requests merged in 2024-01, with the labels that each got.

#1657 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/ingress/1.12/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.12/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.12/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.11.6/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.6/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.6/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.6/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.12.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.12.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.12.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.12.3/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1660 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1661 Do not remove the resources if status.Manifests is empty
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
Labels: approved, lgtm, size/XS

#1659 [release-1.12] Update the maninfests for 1.12
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.11/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.11/kourier/kourier.yaml
  cmd/operator/kodata/ingress/1.12/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.12/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.12/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.8/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.9/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.11.6/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.11.6/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.11.6/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.11.6/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.12.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.12.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.12.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.12.3/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1668 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1670 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.12.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/knative.dev/eventing/pkg/eventingtls/servermanager.go
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1669 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1671 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/common/model/alert.go
  vendor/github.com/prometheus/common/model/metadata.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/github.com/prometheus/common/model/signature.go
  vendor/github.com/prometheus/common/model/silence.go
  vendor/github.com/prometheus/common/model/value.go
  vendor/github.com/prometheus/common/model/value_float.go
  vendor/golang.org/x/crypto/internal/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/internal/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/google.golang.org/protobuf/encoding/protodelim/protodelim.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1672 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.12/istio/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1673 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1674 Eventing TLS: Add trust manager resources to filter
  pkg/reconciler/knativeeventing/eventing_tls.go
Labels: approved, lgtm, size/XS

#1675 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1676 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1677 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1678 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1679 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1680 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1683 Resume the development of 1.14
  test/e2e-common.sh
Labels: approved, lgtm, size/XS
