Repository knative/operator, pull requests merged in 2024-09, with the labels that each got.

#1880 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.14.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/interface.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1882 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1889 For satefulset kafka dispatchers we ignore the replica
  pkg/reconciler/common/ha.go
  pkg/reconciler/common/hpa.go
  pkg/reconciler/common/hpa_test.go
  pkg/reconciler/common/workload_override.go
Labels: approved, lgtm, size/S

#1892 [release-1.14] Update operator bits
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1893 [release-1.15] update operator bits
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.15.1/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1894 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/metadata/CHANGES.md
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/compute/metadata/syscheck.go
  vendor/cloud.google.com/go/compute/metadata/syscheck_linux.go
  vendor/cloud.google.com/go/compute/metadata/syscheck_windows.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/conn/record.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/handshaker.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  vendor/google.golang.org/grpc/credentials/insecure/insecure.go
  vendor/google.golang.org/grpc/credentials/oauth/oauth.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/grpclog/internal/logger.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/channelz/channelmap.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/channelz/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/googlecloud/googlecloud.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/passthrough/passthrough.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/keepalive/keepalive.go
  vendor/google.golang.org/grpc/mem/buffers.go
  vendor/google.golang.org/grpc/resolver/manual/manual.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/stream_interfaces.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1895 Use istio.sidecar.inject label instead of annotation
  config/charts/knative-operator/templates/operator.yaml
  config/manager/operator.yaml
  config/webhook/webhook.yaml
  pkg/reconciler/common/job.go
  pkg/reconciler/common/testdata/manifest.yaml
Labels: approved, lgtm, size/M

#1896 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/manifest.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1897 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/crd.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1898 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/forwarder.go
  vendor/knative.dev/eventing/test/upgrade/prober/receiver.go
  vendor/knative.dev/eventing/test/upgrade/prober/sender.go
  vendor/knative.dev/eventing/test/upgrade/prober/verify.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/104-forwarder.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/knative.dev/serving/test/e2e/httpproxy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
