Repository knative/operator, pull requests merged in 2024-05, with the labels that each got.

#1782 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1783 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1785 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1784 [release-1.14]: Update the deps and manifests for 1.14
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.1/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1786 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1787 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1788 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/crossnamespace/validation.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/rolebinding.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/roles.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/serviceaccount.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/subscription.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1789 Resume the development of 1.15
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1791 Pin the operator to the namespace knative-operator for helm
  hack/generate-helm.sh
Labels: approved, lgtm, size/XS

#1793 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/rolebinding.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/roles.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1794 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.13/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/1.14/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.14/github/github.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.14/redis/redis-source.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/parallel.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/sequence.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1795 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/configstore.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1797 Keep the letter v at the beginning of the version number for helm chart
  hack/generate-yamls.sh
Labels: approved, lgtm, size/XS

#1801 [release-1.14] Update 1.14 branch manifests
  cmd/operator/kodata/eventing-source/1.13/redis/redis-source.yaml
  cmd/operator/kodata/eventing-source/1.14/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.14/github/github.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.14/redis/redis-source.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.13.5/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1803 [release-1.14] Move the Helm artifact to a correct location
  cmd/operator/kodata/eventing-source/1.13/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.13/github/github.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.14/contour/net-contour.yaml
  hack/generate-yamls.sh
Labels: approved, lgtm, size/L

#1805 Removed the namespace in Helm template
  hack/generate-helm.sh
Labels: approved, lgtm, size/XS

#1808 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/upgrade/deployment_failure.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1809 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1810 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1811 [main] Upgrade to latest dependencies
  cmd/operator/kodata/ingress/1.14/contour/net-contour.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.13.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.13.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.13.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.13.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.14.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.14.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.14.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.14.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e/encryption.go
  vendor/knative.dev/serving/test/e2e_constants.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1812 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1813 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_conversion.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
