Repository knative/operator, pull requests merged in 2024-06, with the labels that each got.

#1814 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/auth/CHANGES.md
  vendor/cloud.google.com/go/auth/auth.go
  vendor/cloud.google.com/go/auth/credentials/compute.go
  vendor/cloud.google.com/go/auth/httptransport/httptransport.go
  vendor/cloud.google.com/go/auth/internal/transport/cba.go
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/annotations.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/http.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/resource.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/routing.pb.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/google.golang.org/genproto/googleapis/api/launch_stage.pb.go
  vendor/knative.dev/serving/pkg/networking/util.go
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1815 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.14/istio/net-istio.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sinks/constants.go
  vendor/knative.dev/eventing/pkg/apis/sinks/register.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_types.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_validation.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/fake/fake_jobsink.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/fake/fake_sinks_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/jobsink.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/sinks_client.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sinks/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sinks/v1alpha1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sinks/v1alpha1/jobsink.go
  vendor/knative.dev/eventing/pkg/client/listers/sinks/v1alpha1/expansion_generated.go
  vendor/knative.dev/eventing/pkg/client/listers/sinks/v1alpha1/jobsink.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1816 [release-1.14]: Updated the manifests for release 1.14 operator
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.14/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.14/istio/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.13.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.13.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.13.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.13.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.14.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.14.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.14.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.14.1/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1818 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1819 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/cloud.google.com/go/auth/CHANGES.md
  vendor/cloud.google.com/go/auth/credentials/filetypes.go
  vendor/cloud.google.com/go/auth/grpctransport/grpctransport.go
  vendor/cloud.google.com/go/auth/httptransport/httptransport.go
  vendor/cloud.google.com/go/auth/internal/transport/cert/workload_cert.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/genproto/googleapis/type/date/date.pb.go
  vendor/google.golang.org/genproto/googleapis/type/expr/expr.pb.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1821 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/storage/names/generate.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/eventpoliciesstatus_type.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sinks/register.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_validation.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1alpha1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1alpha1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1823 fix liveness probe removal
  pkg/reconciler/common/workload_override.go
  pkg/reconciler/common/workload_override_test.go
Labels: approved, lgtm, size/S, ok-to-test

#1822 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.13.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.13.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.13.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.13.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.13.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.13.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.14.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.3/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/authstatus/authstatus.go
  vendor/knative.dev/pkg/resolver/authenticatable_resolver.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1824 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
