Repository knative/operator, pull requests merged in 2024-08, with the labels that each got.

#1847 Resume the development of 1.16
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1853 [release-1.15] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.14/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.15/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.15/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.15/kourier/kourier.yaml
  cmd/operator/kodata/knative-serving/1.15.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.15.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.15.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.15.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/boilerplate.go.txt
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1852 [release-1.14] Updated the manifests for release-1.14
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.14/istio/net-istio.yaml
Labels: approved, lgtm, size/L

#1849 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1855 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-serving/1.15.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.15.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.15.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.15.2/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1857 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1859 [release-1.15] Update the manifests for release-1.15
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-serving/1.15.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.15.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.15.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.15.2/4-serving-post-install-jobs.yaml
  hack/generate-bundle.sh
  hack/generate-helm.sh
Labels: approved, size/XXL, lgtm

#1858 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_defaults.go
  vendor/knative.dev/eventing/test/e2e-rekt-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1861 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1867 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/reconciler/testing/v1/eventpolicy.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1872 [release-1.14]: Configure the securityContext, resources and pod annotations in helm
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  config/charts/knative-operator/templates/operator.yaml
  config/charts/knative-operator/values.yaml
  hack/generate-helm.sh
Labels: approved, lgtm, size/L

#1875 Updated the dependencies and manifests
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  pkg/reconciler/knativeeventing/common/defaultbroker.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1878 [release-1.14]: Fixed the podAnnotations issue for the helm chart
  config/charts/knative-operator/templates/operator.yaml
Labels: approved, lgtm, size/S

#1877 [release-1.15]: Configure the securityContext, resources and pod annotations
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  config/charts/knative-operator/templates/operator.yaml
  config/charts/knative-operator/values.yaml
  hack/generate-helm.sh
Labels: approved, lgtm, size/L

#1879 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/L
