Repository knative/operator, pull requests merged in 2024-11, with the labels that each got.

#1930 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/integration_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/integration_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/integration_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/integration_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/integration_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/integrationsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1936 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport_go122.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/source.go
  vendor/golang.org/x/tools/internal/imports/source_env.go
  vendor/golang.org/x/tools/internal/typeparams/free.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/golang.org/x/tools/internal/versions/types.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1931 feat: create helm chart repository in gh-pages
  .github/workflows/publish-helm.yaml
  .gitignore
  hack/find_helm_chart_releases_and_create_helm_index.sh
  hack/gh-pages.tmpl
Labels: approved, lgtm, size/L, ok-to-test

#1940 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
