Repository knative/operator, pull requests merged in 2024-12, with the labels that each got.

#1941 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/requestreply_defaults.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1943 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1945 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1946 [release-1.15] Updated the manifests in 1.15
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.15.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.15.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.15.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.15.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.15.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.15.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.15.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.15.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.15.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.15.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.15.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.15.5/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1949 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
