Repository knative/operator, pull requests merged in 2024-10, with the labels that each got.

#1900 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1868 Added the securityContext and resources into the operator deployment
  config/manager/operator.yaml
  config/webhook/webhook.yaml
Labels: approved, lgtm, size/S

#1901 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1902 [release-1.15] Updated the manifests for 1.15
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.14.7/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1899 Implement the configuration of labels and annotations for the namespace
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/apis/operator/base/common.go
  pkg/reconciler/common/namespace.go
  pkg/reconciler/common/namespace_test.go
  pkg/reconciler/common/transformers.go
Labels: approved, lgtm, size/L

#1913 [release-1.15] Updated the manifests for the release-1.15
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.15.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.15.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.15.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.15.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.15.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.15.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.14.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.14.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.14.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.14.2/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1908 Migrate to use kube codegen in update-codegen.sh
  hack/update-codegen.sh
  pkg/apis/operator/base/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S

#1911 Configure the securityContext, resources and pod annotations in helm
  config/charts/knative-operator/templates/operator.yaml
  config/charts/knative-operator/values.yaml
  hack/generate-helm.sh
Labels: approved, lgtm, size/L

#1912 Allow HTTP->HTTPS redirection on Istio Gateway
  config/crd/bases/operator.knative.dev_knativeservings.yaml
Labels: approved, lgtm, size/S

#1914 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1915 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/auth/verifier.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1916 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1917 [release-1.15] Updated the manifests for release-1.15
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.15.3/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1918 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1919 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1922 [release-1.15] Updated the manifests for release-1.15
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.15/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/hack/boilerplate.go.txt
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1924 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.16/github/github.yaml
  cmd/operator/kodata/eventing-source/1.16/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.16/redis/redis-source.yaml
Labels: approved, size/XXL, lgtm

#1926 Resume the development of 1.17
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1927 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1928 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta3/eventtype.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta3/expansion_generated.go
  vendor/knative.dev/eventing/pkg/eventtype/eventtypes.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1929 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventtype/eventtypes.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
