Repository knative/operator, pull requests merged in 2024-04, with the labels that each got.

#1761 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/cloud.google.com/go/iam/CHANGES.md
  vendor/cloud.google.com/go/iam/apiv1/iampb/iam_policy.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/options.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/policy.pb.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/credentialspb/common.pb.go
  vendor/cloud.google.com/go/iam/credentials/apiv1/credentialspb/iamcredentials.pb.go
  vendor/cloud.google.com/go/iam/internal/version.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/reader.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/eventtype_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta3/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1762 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1763 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1765 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1766 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/net/http/httpproxy/proxy.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1764 add support for podDisruptionBudgets maxUnavailable
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  pkg/reconciler/common/poddisruptionbudget_override.go
  pkg/reconciler/common/poddisruptionbudget_override_test.go
Labels: approved, lgtm, size/L, ok-to-test

#1768 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1770 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1772 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.13/gitlab/gitlab.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1774 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1773 Change the namespace into knative-operator
  config/crd/bases/operator.knative.dev_knativeeventings.yaml
  config/crd/bases/operator.knative.dev_knativeservings.yaml
  config/default/kustomization.yaml
  config/manager/config-logging-configmap.yaml
  config/manager/config-observability-configmap.yaml
  config/manager/operator.yaml
  config/rbac/clusterrole_aggregated_binding.yaml
  config/rbac/fake_clusterrole_aggregated_binding.yaml
  config/rbac/fake_service_account.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/rbac/webhook_role.yaml
  config/rbac/webhook_role_binding.yaml
  config/rbac/webhook_service_account.yaml
  config/webhook/webhook-secret.yaml
  config/webhook/webhook-service.yaml
  config/webhook/webhook.yaml
  hack/generate-bundle.sh
  hack/generate-helm.sh
  test/e2e-common.sh
Labels: approved, lgtm, size/M

#1777 Added the namespace knative-operator
  config/000-namespace.yaml
  config/001-webhook-secret.yaml
  config/002-webhook.yaml
  config/003-webhook-service.yaml
Labels: approved, lgtm, size/S

#1779 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1778 Added the kafka source 1.14
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.14/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.13.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.13.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.13.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.13.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.13.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.13.4/6-eventing-post-install.yaml
  config/rbac/role.yaml
Labels: approved, size/XXL, lgtm
