Repository knative/operator, pull requests merged in 2024-02, with the labels that each got.

#1687 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1686 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/knative.dev/networking/pkg/certificates/certs.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/key_pair.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1689 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-serving/1.12.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.12.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.12.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.12.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.13.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.13.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.13.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.13.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/e2e-common.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1690 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/cba.go
  vendor/google.golang.org/api/internal/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1692 [release-1.12] update the manifests for 1.12
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.11/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.12/istio/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.10/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.12.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.12.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.12.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.12.4/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1693 [release-1.13] Update the manifests for the 1.13
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.11.11/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.13.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.13.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.13.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.13.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.13.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.13.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.12.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.12.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.12.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.12.4/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.13.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.13.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.13.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.13.1/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1695 Added the helloworld as the upgrade test image
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  test/e2e-serving-upgrade-tests.sh
Labels: approved, lgtm, size/L

#1696 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/test/upgrade/deployment_failure.go
  vendor/knative.dev/serving/test/upgrade/postupgrade.go
  vendor/knative.dev/serving/test/upgrade/preupgrade.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1482 Feat: Istio gateway TLS support added
  config/crd/bases/operator.knative.dev_knativeservings.yaml
Labels: approved, lgtm, size/S, ok-to-test

#1697 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1698 Shell executor logs through testing.T in upgrade tests
  test/upgrade/installation/shell.go
  third_party/VENDOR-LICENSE/knative.dev/hack/shell/LICENSE
  vendor/knative.dev/pkg/test/upgrade/shell/executor.go
  vendor/knative.dev/pkg/test/upgrade/shell/fail-example.sh
  vendor/knative.dev/pkg/test/upgrade/shell/prefixer.go
  vendor/knative.dev/pkg/test/upgrade/shell/project.go
  vendor/knative.dev/pkg/test/upgrade/shell/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1699 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/receiver/services.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1702 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1703 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1704 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, skip-review

#1705 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/defaults.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/config/structure.go
  vendor/knative.dev/eventing/test/upgrade/prober/wathola/event/services.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1706 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1707 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-external-domain-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1709 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1710 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1715 Change the doc on the deployments of the operator
  .codecov.yaml
  DEVELOPMENT.md
Labels: approved, lgtm, size/XS

#1719 [release-1.13] Updated the manifests for release-1.13
  .codecov.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.11/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.12/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.13/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.12.5/6-eventing-post-install.yaml
  test/e2e-common.sh
  test/e2e-eventing-upgrade-tests.sh
  test/e2e-serving-upgrade-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, size/XXL, lgtm

#1718 Removed the additional line
  CONTRIBUTING.md
  test/e2e-common.sh
  test/e2e-eventing-upgrade-tests.sh
  test/e2e-serving-upgrade-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, lgtm, size/S

#1720 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/generated_expansion.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/networking_client.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/realm.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL
