Repository knative/operator, pull requests merged in 2025-01, with the labels that each got.

#1951 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/test/e2e-external-domain-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1952 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1953 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1955 Updated the CI kubernetes version to 1.30
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#1957 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_helpers.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1959 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#1960 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/trigger.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/requestreply.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta3/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/parallel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/sequence.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/channel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/subscription.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/integrationsink.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sinks/v1alpha1/jobsink.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/integrationsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1alpha1/eventpolicy.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1alpha1/requestreply.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta3/eventtype.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/podscalable_types.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_defaults.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/knative.dev/serving/pkg/networking/util.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/e2e/autoscale.go
  vendor/knative.dev/serving/test/e2e/e2e.go
  vendor/knative.dev/serving/test/e2e/httpproxy.go
  vendor/knative.dev/serving/test/e2e/scale.go
  vendor/knative.dev/serving/test/e2e/websocket.go
  vendor/knative.dev/serving/test/prober.go
  vendor/knative.dev/serving/test/upgrade/deployment_failure.go
  vendor/knative.dev/serving/test/upgrade/preupgrade.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1963 Removed the directory kodata for webhook
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/refs
Labels: approved, lgtm, size/XS

#1964 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#1962 Support specifying affinity in Helm chart
  config/charts/knative-operator/templates/operator.yaml
  config/charts/knative-operator/values.yaml
Labels: approved, lgtm, size/S, ok-to-test

#1968 [release-1.15] Added the serving manifest at 1.15.3
  cmd/operator/kodata/knative-serving/1.15.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.15.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.15.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.15.3/4-serving-post-install-jobs.yaml
Labels: approved, lgtm

#1970 Added the eventing sources to release for 1.17
  cmd/operator/kodata/eventing-source/1.17/github/github.yaml
  cmd/operator/kodata/eventing-source/1.17/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.17/redis/redis-source.yaml
  cmd/operator/kodata/knative-serving/1.15.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.15.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.15.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.15.3/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#1972 Added 1.17 eventing kafka
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-source.yaml
Labels: approved, size/XXL, lgtm

#1973 Resume the development of 1.18 for Operator
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.sh.txt
  test/e2e-common.sh
Labels: approved, lgtm, size/S

#1974 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1977 feat: add workflow_dispatch to publish helm workflow, remove unneeded fetch
  .github/workflows/publish-helm.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test, ok-to-test

#1982 feat(helm): Create .gitignore in gh-pages
  .gitignore
Labels: approved, lgtm, size/XS, ok-to-test

#1983 feat(helm): make PR with changes to deal with branch protection rules
  .github/workflows/publish-helm.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test, ok-to-test

#1985 Updated the indentation issue in the template
  config/charts/knative-operator/templates/operator.yaml
  hack/generate-helm.sh
Labels: approved, lgtm, size/M
