Repository knative/operator, pull requests merged in 2025-05, with the labels that each got.

#2086 [release-1.17] Updated the manifests for 1.17 branch
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-serving/1.17.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.17.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.17.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.17.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#2091 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.17.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.18.1/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.18.1/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.18.1/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.18.1/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.18.1/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.18.1/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.17.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.17.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.17.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.17.1/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/typeutil/callee.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/stdlib/stdlib.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#2092 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/serving/test/e2e-external-domain-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2094 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2096 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2097 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2098 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/eventingtls/trust_bundle.go
  vendor/knative.dev/eventing/test/rekt/features/channel/eventing_tls_feature.go
  vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go
  vendor/knative.dev/eventing/test/rekt/resources/configmap/config-features.yaml
  vendor/knative.dev/eventing/test/rekt/resources/configmap/configmap.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2099 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
