Repository knative/operator, pull requests merged in 2025-03, with the labels that each got.

#2007 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtransform_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2013 Fix the Istio setup in CI
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.17.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.17.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.17.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.17.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.17.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.17.3/6-eventing-post-install.yaml
  test/e2e-common.sh
Labels: approved, size/XXL, lgtm

#2016 Unset env.ValueFrom in ImageTransform
  pkg/reconciler/common/images.go
Labels: approved, lgtm, size/XS

#2023 [release-1.16] Fixed the CI issue
  .codecov.yaml
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.16/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.16.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.16.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.16.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.16.3/4-serving-post-install-jobs.yaml
  test/e2e-common.sh
Labels: approved, size/XXL, lgtm

#2010 Wait for deployments
  pkg/reconciler/common/deployments.go
  pkg/reconciler/common/deployments_test.go
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
  pkg/reconciler/common/stages.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
  pkg/reconciler/manifests/install.go
  pkg/reconciler/manifests/install_test.go
Labels: approved, lgtm, size/L

#2029 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/integration_sink_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2038 [release-1.17] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.16/rabbitmq/rabbitmq-source.yaml
Labels: approved, lgtm, size/M

#2039 [release-1.16] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.16/rabbitmq/rabbitmq-source.yaml
Labels: approved, lgtm, size/M

#2037 [release-1.15] Wait for deployments (#2010)
  pkg/reconciler/common/deployments.go
  pkg/reconciler/common/deployments_test.go
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
  pkg/reconciler/common/stages.go
  pkg/reconciler/knativeeventing/knativeeventing.go
  pkg/reconciler/knativeserving/knativeserving.go
  pkg/reconciler/manifests/install.go
  pkg/reconciler/manifests/install_test.go
Labels: approved, lgtm, size/L

#2036 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.16/rabbitmq/rabbitmq-source.yaml
  go.mod
  go.sum
  vendor/github.com/cloudevents/conformance/pkg/event/event.go
  vendor/github.com/cloudevents/conformance/pkg/event/read.go
  vendor/github.com/cloudevents/conformance/pkg/event/write.go
  vendor/github.com/cloudevents/conformance/pkg/http/http.go
  vendor/github.com/cloudevents/conformance/pkg/http/raw.go
  vendor/knative.dev/eventing/pkg/apis/common/integration/v1alpha1/aws.go
  vendor/knative.dev/hack/boilerplate.go.txt
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2040 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/common/integration/v1alpha1/aws.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2042 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#2045 Bump github.com/golang-jwt/jwt/v4 from 4.5.1 to 4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2046 [release 1.17] Golang jwt/v4 4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2047 [release-1.16] Use 4.5.2 version of golang-jwt
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2044 fix: publish all helm charts
  hack/find_helm_chart_releases_and_create_helm_index.sh
Labels: approved, lgtm, size/M, ok-to-test
