Repository knative/operator, pull requests merged in 2025-04, with the labels that each got.

#2051 Updated the manifests and deps
  cmd/operator/kodata/knative-eventing/1.16.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#2050 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2053 Upgrade to golangci yaml v2
  .golangci.yaml
Labels: approved, lgtm, size/S

#2056 [release-1.17] Upgrade to golangci.yaml v2
  .golangci.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.17.4/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/common/integration/v1alpha1/aws.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#2057 [release-1.16] Upgrade to golangci.yaml v2
  .golangci.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.6/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#2061 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#2065 [release-1.17] Updated the manifests in the branch 1.17
  cmd/operator/kodata/eventing-source/1.16/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.16/github/github.yaml
  cmd/operator/kodata/eventing-source/1.16/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.16/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.16/contour/net-contour.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.17.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.17.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.17.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.17.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.17.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.17.5/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#2066 [release-1.16] Updated the manifests for the branch 1.16
  cmd/operator/kodata/eventing-source/1.16/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.16/github/github.yaml
  cmd/operator/kodata/eventing-source/1.16/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.16/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.16/contour/net-contour.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.7/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#2069 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2070 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2071 [release-1.17] Updated the dependencies for 1.17
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#2072 [release-1.16] Updated the dependencies for 1.16
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#2077 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#2080 Resume the development of 1.19
  test/e2e-common.sh
Labels: approved, lgtm, size/XS

#2082 [main] Format Go code
  pkg/reconciler/common/workload_override_test.go
Labels: approved, lgtm, size/XS

#2083 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/endpointsharding/endpointsharding.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/service/service.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/transport/client_stream.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/server_stream.go
  vendor/google.golang.org/grpc/resolver/manual/manual.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#2085 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
