Repository knative/operator, pull requests merged in 2025-09, with the labels that each got.

#2135 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-source.yaml
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/L, skip-review

#2138 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.19/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.19/github/github.yaml
  cmd/operator/kodata/eventing-source/1.19/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.19/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.19/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.19/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.19/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.19/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.19.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.19.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.19.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.19.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.19.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.19.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.19.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.19.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.19.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.19.3/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.19.4/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.19.4/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.19.4/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.19.4/4-serving-post-install-jobs.yaml
Labels: size/XXL, skip-review

#2140 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, skip-review

#2143 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/fuzz.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/github.com/prometheus/common/model/value.go
  vendor/github.com/prometheus/common/model/value_histogram.go
  vendor/github.com/prometheus/common/model/value_type.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/google.golang.org/protobuf/internal/genid/api_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/queue_metrics.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: size/XXL, skip-review

#2146 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/modules.txt
Labels: size/S, skip-review

#2150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/string_to_string.go
  vendor/github.com/spf13/pflag/time.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/gotrack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/unix/affinity_linux.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/packages/visit.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/go/types/typeutil/map.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport_go122.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/modules.txt
Labels: size/XXL, skip-review

#2152 [release-1.18] Updated the manifests for operator 1.18
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.17/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/ingress/1.18/istio/net-istio.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.17.6/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.18.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.18.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.18.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.18.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.18.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.18.2/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.18.3/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.18.3/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.18.3/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.18.3/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.18.3/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.18.3/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.17.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.17.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.17.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.17.2/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.18.1/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.18.1/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.18.1/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.18.1/4-serving-post-install-jobs.yaml
Labels: approved, size/XXL, lgtm

#2154 [main] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-source.yaml
Labels: size/L, skip-review

#2148 [release-1.19] Upgrade to latest dependencies
  cmd/operator/kodata/eventing-source/1.19/ceph/ceph.yaml
  cmd/operator/kodata/eventing-source/1.19/github/github.yaml
  cmd/operator/kodata/eventing-source/1.19/gitlab/gitlab.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-controller.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-post-install.yaml
  cmd/operator/kodata/eventing-source/1.19/kafka/eventing-kafka-source.yaml
  cmd/operator/kodata/eventing-source/1.19/rabbitmq/rabbitmq-source.yaml
  cmd/operator/kodata/eventing-source/1.19/redis/redis-source.yaml
  cmd/operator/kodata/ingress/1.18/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.19/contour/net-contour.yaml
  cmd/operator/kodata/ingress/1.19/istio/net-istio.yaml
  cmd/operator/kodata/ingress/1.19/kourier/kourier.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.18.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.19.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.19.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.19.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.19.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.19.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.19.4/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-eventing/1.19.5/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.19.5/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.19.5/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.19.5/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.19.5/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.19.5/6-eventing-post-install.yaml
  cmd/operator/kodata/knative-serving/1.19.5/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.19.5/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.19.5/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.19.5/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.19.6/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.19.6/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.19.6/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.19.6/4-serving-post-install-jobs.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/auth/verifier.go
  vendor/knative.dev/eventing/pkg/utils/utils.go
  vendor/knative.dev/pkg/controller/queue_metrics.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/modules.txt
Labels: size/XXL, skip-review

#2159 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1/configuration.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: size/M, skip-review
