Repository knative/operator, pull requests merged in 2025-02, with the labels that each got.

#1989 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/spf13/pflag/.editorconfig
  vendor/github.com/spf13/pflag/.golangci.yaml
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#1990 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.17.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/name/registry.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#1991 [release-1.17] Added eventing 1.17.2
  cmd/operator/kodata/knative-eventing/1.17.2/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.17.2/6-eventing-post-install.yaml
Labels: approved, size/XXL, lgtm

#1992 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/serverlessservice.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#1994 [release-1.16] Upgrade the Kubernetes version in CI
  cmd/operator/kodata/knative-serving/1.15.3/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.15.3/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.15.3/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.15.3/4-serving-post-install-jobs.yaml
  cmd/operator/kodata/knative-serving/1.16.2/1-serving-crds.yaml
  cmd/operator/kodata/knative-serving/1.16.2/2-serving-core.yaml
  cmd/operator/kodata/knative-serving/1.16.2/3-serving-hpa.yaml
  cmd/operator/kodata/knative-serving/1.16.2/4-serving-post-install-jobs.yaml
  test/e2e-common.sh
Labels: approved, size/XXL, lgtm

#1998 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1999 [main] Upgrade to latest dependencies
  cmd/operator/kodata/knative-eventing/1.16.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/6-eventing-post-install.yaml
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/integration_sink_types.go
  vendor/knative.dev/eventing/pkg/eventingtls/eventingtls.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#2001 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go
  vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#2003 [release-1.16] Updated the manifests and dependencies for 1.16
  .golangci.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/1-eventing-crds.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/2-eventing-core.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/3-eventing-tls-networking.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/4-in-memory-channel.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/5-mt-channel-broker.yaml
  cmd/operator/kodata/knative-eventing/1.16.4/6-eventing-post-install.yaml
  go.mod
  go.sum
  test/e2e-common.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#2005 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#2006 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
